---
title: "Richard Careaga Interview 2018-10-29"
author: "Richard Careaga"
date: "10/23/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dear Tracy,

To give you an understanding of where I stand in terms of many of the standard questions, here's a self-evaluation that will give you the option of more pointed questions or the scope to range further afield. This page is hosted on a private S3 bucket with public access limited to this page, which will be closed after we talk.

# How I Relate to Amazon's Leadership Principles

** Customer Obsession

> I've been an Amazon customer since the time when Jeff was still dropping books and the website was hand coded. In all that time, I've only had one negative experience -- a mass market paperback of a long out-of-print series being revivied. Most were priced under $15; this one was over $50, and the associate said "that's what the system says, so it must be right." I called the publisher, and it got straightened out. Out of hundreds of other transactions, never a glitch.

I approve.

## Ownership

The long-view is hard to find; the short-view opportunity today creates crises next year. 
 
## Invent and Simplify

Any darned fool can make things complicated. It takes hard work to make them simple. Simplicity begets 
#Leaders are right, A Lot

People confuse leaders with posistion. I managed a staff of six in my first job out out school; I've been an individual contributor ever since. I've lead by understanding the culture that I was trying to influence, giving them bright-line rules to live by when the risks were low and the issues simple, and spent a lot time explaining how the risks could cascade and more nuanced thinking was called for. 

Learning that one is wrong is the best thing that can happen to a leader, if it happens early and becomes internalized as a pattern. As a junior lawyer I was negotiating hot and heavy to hold a minor party to a high standard. The more senior lawyer across the table took off his glasses, rubbed his eyes and told me: "Richard, you don't understand. My client is making only $2,400 a year for its services." This was on a $30 million transaction. I learned.

## Learn and Be Curious

Aùn aprendo, say Francisco Goya toward the end of his long life of artistic genius -- "I'm still learning." Goya was fortunate that what there was to learn during his era were not new technologies of paint, brushes and canvas but the infinite possibilities of vision. A leader cannot repeat the same year of learning the internals of the latest technologies every year throughout a career spanning decades. The leader must focus with maturity on implications, not implementation.
 
## Hire and Develop the Best

You may have heard of Parkingson's Law: *Work expands to fill the time available for it.* He was an asute obversor of organizational culture, and he also said *officials multiply subordinates, not rivals.* During my years at WaMu, I lobbied hard for the hiring of four colleagues, all of whom would put me out of one or the other parts of my fiefdom. I ended up reporting to one of them, even though I outranked him.

## Leaders raise the performance bar with every hire and promotion

At my last job, there was something of a revolving door of skilled assistants, and my colleagues often took the view that the best way to reduce turnover was to give tepid reviews. My attitude in recruting a shared assistant was different: *I want you to thrive. It takes time to learn a new organization, and it takes time for me to show you how best you can help me do my job. Give me a 9-12 month commitment to learning how I work and how the organization works, find and train your successor and I will do everything in my power to help you get to the next level. That worked well.
They recognize exceptional talent, and willingly move them throughout the organization. Leaders develop leaders and take seriously their role in coaching others. We work on behalf of our people to invent mechanisms for development like Career Choice.

## Insist on the Highest Standards

Leaders have relentlessly high standards - many people may think these standards are unreasonably high, and so did my colleagues when I pointed out sloppy numbers, poorly describe product features, and inadequate fact checking. And the $450/hour average rate outside lawyers I hired didn't much appreciate when I called them out for running up bills on cookie cutter transactions. I had worked hard over the years to create stanardized documentation that isolated deal specific terms, and felt that my client should have the benefit of those efficiencies.
 
## Think Big

Thinking *in small results* is a self-fulfilling prophecy, as in thinking in marginal improvements. A  hemibel is worth dicussing, a 2% improvement is a rounding error. The *bold direction* that leaders should spend their time on revolve around Peter Drucker's classic questions of *what **is** our business? What **should** it be? Once we know that, we know where to innovate and market. And by market, he did not mean advertise, he meant demonstrating what Amazon and Apple to so well, of introducing products and services that customers did not yet know they needed.

 
## Bias for Action

Speed matters in business, but all too many fall in love with their problems, and they would feel deprived without remote contingencies to worry about. As the Grammy-Academic-Nobel Prize winning musician sang *he's that not busy being born is busy dying.*
 
## Frugality

Accomplish more with less. Henry Ford, with all the deplorable social attitudes of a man of his day almost a century ago had a beautiful observation: *The most beautiful things in the are those from which all excess weight has been removed.* In this, he was on an industrial artistic par with Leon Battista Alberti: *Beauty is the harmony and concord of all parts, achieved in such a manner that nothing could be added or taken away or altered except for the worse.*
- 
 
## Earn Trust

Leaders know that the opposite of listening is not speaking, but composing a response. They also know that corporate euphemisms breed mistrust like cochroch mating  pairs. (In my last job, my termination date  was spoken of as my *graduation date.* A leader who can say, *we screwed up, because of my decision. What did I miss when you told me of the risks. And if you didn't, remember that this is an organization that prefers hard edged, well argued criticism to happy talk.

## Dive Deep

If you remember the six-inch stacks of green and white striped mainframe printout, you rememeber also the CFO pouring over them, past the grand totals and the subtotals down to the line items. It's the only way they could have confidence in the balance sheet and income statements that they would have to defend to the board of directors' audit committee and outside accountants. We've lot a lot of that in many industrys with the fashion of KPIs, which are easily gamed as you know if you're a fly on the wall listening to someone bragging about fattening a bonus by accelerating income into the year-end quarter.

 
## Have Backbone; Disagree and Commit

Leaders are obligated to respectfully challenge decisions when they disagree, even when doing so is uncomfortable or exhausting. Leaders have conviction and are tenacious. They do not compromise for the sake of social cohesion. Once a decision is determined, they commit wholly. *That sounds a lot like the Marine Corps my father served in during the Second World War until his death at 94, when he referred to himself as a gunnery sergeant on temporary leave.""

 
## Deliver Results

Leaders focus on the key inputs for their business and deliver them with the right quality and in a timely fashion. Despite setbacks, they rise to the occasion and never settle. *The key here is **inputs,** which are objective, not outputs, which can be gamed.

# Behaviors

## Tell me about a time when you were faced with a problem that had a number of possible solutions. What was the problem and how did you determine the course of action? What was the outcome of that choice?

I was retained to prepare a state environmental assessment on the multitude permits required to construct a new regional shopping center. The client had found an ideal site from a commercial standpoint that also managed to push almost every environmental hot button in the region. My job was to assess a design in progress, understand the environmental setting, and design an application project with the best chance of success.

During my survey, I quickly discovered several issues, some of which were routine, and others unique. The site was located on the periphery of an unusual natural habitat being encroached on by development. One of the most prized features of the habitat was it was the home of an endangered species of butterly. And not just any butterfly. It was described by the famous novelist Vladimer Nabovof. It has extremely specific habitat requirements found only in the surrounding area. And it looked as if it were designed by the finest artists as a poster child for endangered butterflies. It is about the size of a thumbnail with pale blue wings, dark blue stripes and flecks of gold. It may a well been a character in a Disney movie.

So, I went looking through the hitherto unknown wetlands and the heavy second growth forest of the 170-acre site in the 90 ºF/ 100% humidity weather and found a two-acre clearing on a hilltop with abundant blue lupine being devoured by *Melissa samuelis samuelis,* the endangered species.

I'm a geologist, what do I know? Are these a few outliers? I go to a big-name university and recruit a graduate student in leipidoptery (who kept insisting he was a *moth* guy) and we came back for the second breeding season later in the summer. To estimate the population size, you swing the butterfly net, record any previously seen specimens, and tattoo the newcomers with a Sharpie, which was my job. This mark-release-recapture provides a good metric of population size.

*Richard*, Dale told me, *this is the largest population of this species known to science.* 

Whoa! What do I do? Tell the development, *too bad*? Or try to get some context? Obviously, the latter, and Dale and I go exploring and find the *second* largest concentration -- in an industrial park. It turns out that the Karner Blue Butterfly doesn't care much about anything other than its exclusive food source, the blue lupine flower. So, ours can live in peaceful harmony with a mall, right?

Well, not really. People working around industrial parks are unlikely to pull up lupines or swish butterfly nets. People and their kids visiting shopping malls might behave differently.

What to do? The habitat on the hilltop stood atop a small forested rise with a two-acre footprint. Right were one of the department stores was slated. 

It boils down to two alternatives: Tell the developer, *gee, this is tough, you might have problems." * or what I actually said *Bob, I can guarantee you if you don't give up the Nieman Marcus and redo the plan with one few anchor to make room for a habitat protection zone, I guarantee you that the project is dead."

The rest of permitting took four years. Twenty years latter the little critters were doing fine.

## When did you take a risk, make a mistake, or fail? How did you respond, and how did you grow from that experience?

When my employer was acquired by a bank at the same time the accounting rules changed, I failed to add the reciprocal of *pi* to *e* and overlooked the effect on which this change would have on year-end transactions amounting to hundreds of billions. Fortunately for me, my colleague was a CPA, understood the issue and came up with the just-in-time solutation. I copied my master (who moved on six months later) and became an expert in FAS 125 and its successor FAS 140, offshoot FIN 46-R and the other subtlies in accounting (of which there were many) that affectted my work and achieving the results the bank was seeking.

## Describe a time you took the lead on a project.

There are two, one ancient, and the other in the not distant past.

The ancient problem arose during the pre-PC era. At that time a "mini-computer" weighted 400kg and the lights dimmed when you turned it on. I had been hired as the first city planner of a *really* remote Alaska municipality (think 2000 miles north of Honolulu) when the state was awash in oil royalties and looking to spreak the wealth among the rural parts of the state for needed development.

My community did need development. It was build on the remains of an abanodond WWII military base, lacked sewers, treatment plans, reliable water supply, a public dock, sanitary landfill, a code of municipal ordinances that the visiting magistrate would enforce, and the list went on. It even lacked any map to show accurately property boundaries and street rights-of-way. Oh, and it had a 4,000 foot gravel runway with an impossibly short missed approach and a terminal housed in a quonset hut.

The town's permanent popuation had ground by a factor of ten in as many years and swelled to five times as many in fishing season. There was little scarscity of worthwhile and urgent infrastructure projects to be planned, designed, contracted and built.

There was, however, a soft infrastructure problem in City Hall -- shoebox accounting. The outside auditors came through once a year to balance the checkbook, the payroll took eight clerks working a full week twice a month to process the payroll, and the police department batteries were charged to the rudimentary electric utility because they were, well, you know, electric.

Not long after I arrived in February, I figured out that as much as the great State of Alaska wanted to help remedy these problems it would be rightly concerned with how the tens or hundreds of million would properly be accounted for. It didn't take a genius to figure out that the state would find grantees better prepared to document their expenditures.

I talked to the city manager, the treasurer, the mayor, and utlimately the city council about this and brought them around to the same conclusion. How much, they asked. I think we could do it for $100K. All right, they said, without bothering to inquire whether anyone had the knowledge, training and experience to spend that amount, arrange for installation, configure the system, figure out how to use it and train staff. It was one of the both neat and scary things about rural Alaska at the time -- if you were on the ground, it didn't matter much about experience if you were available.

In July we ran our first payroll, to the great anxiety of the City Treasurer who envisioned an angry mob of city workers who hadn't been paid. By September, one junior clerk was able to do the payroll in a half day twice a month. And, in the meantime, I created a general ledger and got the payroll to flow into that. I never did figure out adjusting journals, when I suggested it was time to get a finance director. After that, I rationalized and automated the city budget and enlisted everyone in city hall who could type to create a model municipal code that would actually be enforceable.

The more recent experience was when my Fortune 50 employer, a bank holding company, decided to set up an in-house broker-dealer underwriter for its business in mortgage backed securities. At that time, I was fairly expert in one aspect of the problem, the issuance side, fairly innocent of the special banking regulations, and somewhat confused about the laws governing the sale of securities by broker dealers. 

I arrived in February. In May, I got an invitation from a senior lawyer to sit in on a meeting to discuss a rather overwrought discussion of the banking regulations, which, frankly, I had a hard time following. In June, the senior lawyer said, *you know a lot about this stuff, Richard, why don't you handle it?*

This was the beginning of a four-part process: (1) interviewing the newly hired management to determine what, exactly, they wanted to be able to do, (2) digesting the outside cousnel memo on what, exactly various parts of the organization were *permitted* to do, and (3) recommending the optimal compromise, for the time being betweeen *want/can*.

At that point, I went to my boss and said, *Ok, the logjamb is broken, we really need someone who knows what they're doing to get this outfit off the ground."* To which he said, *the CEO wants this up and running by the end of the year. We don't have time to find someone else. You do it.* I asked, *you mean in addition to [long list of other, mostly unrelated things I was already doing]*. **Just do it.**

It got done, on time. Not the most enjoyable part of my career.

## What did you do when you needed to motivate a group of individuals or promote collaboration on a particular project?

I supported a business that, from a legal standpoint, was 50% law and 50% lore. It had been that way for many years when the regulator announced a reform in the patchwork regime of ad hoc regulation and informal guidance that we had been working under. The changes effect everyone from the "manufacturers" of the mortgage loans involved to the "packagers" to the "issuers" to the "sellers" to the "servicers," along with Treasury, accounting and audit. 

The changes were to go into effect in 18 months after an announcement of the proposed regulations, comments, final regulations and a short implementation period. Just to make things more spicy, mid-way through the process, the regulators threw in a related, more general, set of overlapping regulations that required not a little strategizing on how to maximize marketing effectiveness while limiting liability.

I got involved almost at day one by wrangling an invitation on an American Bar Association panel with the lead regulator to discuss the changes. I participated as a member of the leadership committee to comment on the regulations when they were released, and set outside counsel to participate in the regularor's *pilot program* to come up with a concrete example of how the changes would work in practice.

In the meantime, I briefed the affected business units, emphasizing how much would be old wine in new bottles and highlighting the few requirements that would require new procedures. Needless to say, there was a lot of angst and much of my time was assuring business units that this was something they could adapt to readily.

When the regulations went into effect, we were the first to market, earning a few extra dollars in the process. In a perhaps unprecedented move, due to our participation in the pilot program, we submitted our draft registration statement on the last business day of the year and it was declared effected on the first business day of the following year, three days later, in the amount of $100 billion.

There was more reassurance to come, in terms of mapping what we were already doing to how we would have to do it slighty differently, but in the end everyone got comfortable with the unknown and continued doing good work, considering a rapidly changing economic environment.

## How have you leveraged data to develop a strategy?

The real world keeps intruding on our dreams. When my employer's business collapsed due to a financial panic, I assembled an otherwise unavailable database of 125,000 loans with 50 characteristics to determine root causes of loan failure s(in a three month period, I had to learn MySQL, Python and R and scrape the 14 public webpages and 75 semi-public spreadsheets into usable form.) My work developed too late to prevent the continued issuance of similar loans in future securities due to market collapse, but the database fouond a secondary use in remediation of potentially defaulting loans by providing quickly the required data that the systems of record could not).
