---
title: "Well said"
date: "2018-09-30"
---

A collection of short thoughts.

> ... but we struggle to provide realistic assessments of uncertainty. Also consider the problem that big data suggests a massive number of hypotheses with less protection against the danger of false positive results.

"When small data beats big data" by Julian Faraway and Nicole Augustin https://goo.gl/LhAPh5
<hr>
> Right now my field must tackle describing a world where falling in love, going to war and filling out tax forms looks the same; it looks like typing.

[Quinn Norton](https://goo.gl/fGb6BM)
<hr>
> Many who burnt heretics in the ordinary way of their business were otherwise excellent people.

G. M. Trevelyan, Bias in History
<hr>

> It’s easier to ask forgiveness than than it is to get permission.

Admiral Grace Hopper (created human-readable source code, against all conventional wisdom)
<hr>

> The poverty of time makes beggars of us all

[Jack Boger](https://www.nytimes.com/2018/08/02/magazine/marine-combat.html)
<hr>
> unless you have an indefinitely extensible repertoire of ways to use your candidate belief (if that is what it is) in different contexts, it is not a belief in any remotely recognizable sense.

Daniel Dennett, *Intuition Pumps and Other Tools for Thinking*
<hr>
> If the intent is to insult, then is it really such a shock that people could feel insulted?

[Vox](http://bit.ly/1GKKRVo)
<hr>
> But this, too, was a minor threat. Langone was simply threatening to withhold money. Now, as the pope prepares a major encyclical on climate change, to be released this summer, the billionaires are spending a great deal of their money in a direct assault on him. They are calling in their chits, their kept scientists, their rigged conferences, their sycophantic beneficiaries, their bought publicists to discredit words of the pope that have not even been issued: “He would do his flock and the world a disservice by putting his moral authority behind the United Nations’ unscientific agenda on the climate,” they say. They do not know exactly what the pope is going to say in his forthcoming encyclical on preserving God’s creation, but they know what he will not say. He will not deny that the poor suffer from actions that despoil the earth. Everything he has said and done so far shows that Francis always stands for the poor.

[Gary Wills](http://bit.ly/1I6vdI0)
<hr>
> I think it’s important to understand that if this Court concludes that this issue should be left to the political process, what the Court will be saying is that the demeaning, second-class status that gay and lesbian couples now inhabit in states that do not provide for marriage is consistent with the equal protection of the laws. That is not a wait-and-see. That is a validation.

Solicitor General Donald B. Verrilli Jr.
<hr>
[NYT](http://nyti.ms/1KvEmcT)

> Although the United States accounts for about 5 percent of the world’s population, it houses nearly 25 percent of the world’s prison population.

[Hon.Jed S. Rakoff](http://bit.ly/1GY7Te7)
<hr>
> Let us concede this much to the political order: to suffer kings patiently when unworthy, to hide their vices and to encourage their indifferent actions with our approbation – while their authority needs our support.

Montaigne, *Essays* (M.A. Screech, *tr.*)
<hr>
> If an institution is too big to fail, it is too big to exist, and that is the bottom line.

Senator Bernie Sanders, quoted in [NYT](http://nyti.ms/1ReXwbH)
<hr>
> Never mind if the obscenities were imagined—“Louie Louie” promised its listeners stronger stuff. As a member of the Flint Junior Woman’s Club argued, with admirable logic, in a 1965 letter to J. Edgar Hoover, it hardly mattered what the actual lyrics were when “every teenager in the country ‘heard’ the obscene not the copywritten [sic] lyric.”

Anwen Crawford in the [New Yorker](http://nyr.kr/1IO9Fk9)
<hr>
> The music of all creatures has to do with their loves, even of toads and frogs. Is it not the same with man?

Thoreau, *Journal*, May 6, 1854
<hr>
> Insofar as conservatives identify the erosion of the traditional family as a cause of civic disorder, the erosion is not limited to minority communities in Democratic cities. These trends are increasingly characteristic of white communities in red states.

Thomas B. Edson in [NYT](http://nyti.ms/1IOdUMP)
<hr>
> It is only in the middle classes, Stephen, that people get into a state of dumb helpless horror when they find that there are wicked people in the world. In our class, we have to decide what is to be done with wicked people; and nothing should disturb our self possession.

Lady Britomart, *Major Barbara* by G.B.  Shaw
<hr>
> It appears as if the giant party difference in support for abortion under any and all conditions is an artifact of the way the typical abortion survey question is constructed.

Lynn Vavreck in [NYT](http://nyti.ms/1QnrJDY)
<hr>
> all canons of reputability and decency, and all standards of consumption, are traced back by insensible gradations to the usages and habits of thought of the highest social and pecuniary class—the wealthy leisure class.

Thorstein Veblen, *Theory of the Leisure Class*
<hr>
> There is something to be said about going for fat, complacent industries.

Herbert Hovencamp, speaking of *stodgy* incumbent  wireless providers, quoted in [NYT](http://nyti.ms/1P4moUZ)

> "I think the answer is, it’s okay to addict people as long as your business model doesn’t depend on it," he said, as if finally finding the answer to a problem that had long seemed without a solution. "That’s the answer," he added. "That’s the answer." by Andrew Thompson

[Slot machines perfected addictive gaming. Now, tech wants their tricks The Verge via NextDraft]: http://nxt.fm/1P4n"10S 
<hr>
> The family and the group are the essential social unit.

David Brooks in [NYT](http://www.nytimes.com/2015/05/08/opinion/mothers-and-presidents.html)
<hr>
> America didn’t need to make hard choices in the aftermath of crisis. What they needed, instead, was hard thinking — a willingness to understand that this was a special environment, that the usual rules don’t apply in a persistently depressed economy, one in which government borrowing doesn’t compete with private investment and costs next to nothing.

[Krugman](http://nyti.ms/1KRBKGB)
<hr>
> You make a check list: timing, receiver, GPS, transmitter from the receiver to the detector, ... you check everything.

[Data That Threatened to Break Physics](http://bit.ly/1EpVhIM)
<hr>
> Is there a moral here? I think it is that the world is a very complicated place, and it’s way too easy to miss what you should see even if your analytical framework is pretty decent. For me, at least, the great crisis came as a surprise but not a shock, something I didn’t see coming but not a deep problem for my sense of how the world works. Still, I do wish I’d paid more attention to the right things.

[Krugman](http://nyti.ms/1EXO06n)
<hr>
> Politics are possible in the church, as in the university, because power is dispersed and the combatants are protected from dismissal.

Adam Gopnik

[New Yorker](http://nyr.kr/1QUUCbSr)
<hr>
> This shared property, the meaning (of the two sentences in their respective languages), or the content (of the beliefs they express), is a central topic in philosophy and cognitive science. This aboutness that, for example, sentences, pictures, beliefs, and (no doubt) some brain states exhibit, is known in philosophical jargon as intentionality , an unfortunate choice as a technical term, since outsiders routinely confuse it with the everyday idea of doing something intentionally (as in “Are your intentions honorable?”).

Daniel Dennett, *Intuition Pumps and Other Tools for Thinking*
<hr>
> This linkage reveals the absorbing paradox at the heart of language’s origins. As hardwired as it is, language is a distributed object, both across the human brain and across generations of people. And it is precisely the chaotic hot-potato toss of words and grammar that yields the order and beauty that we see today. In the realm of language, as in other things, modern science is showing us that we are not the pilots of our own sealed ship, but are actors in a play, each able to contribute a verse.

[The Family That Couldn’t Say Hippopotamus - Issue 24: Error - Nautilus](http://nautil.us/issue/24/error/the-family-that-couldnt-say-hippopotamus-rp)
<hr>
> I proposed folk psychology as a term for the talent we all have for interpreting the people around us— and the animals and the robots and even the lowly thermostats— as agents with information about the world they act in ( beliefs ) and the goals ( desires ) they strive to achieve, choosing the most reasonable course of action, given their beliefs and desires. Some researchers like to call folk psychology “theory of mind” (or just TOM), ...

> The power and ease of use of folk psychology is due, I have argued, to the simplifying assumptions that enable it. It is like an idealized model in science— maximally abstract and stripped down to the essentials. I call this the intentional stance.

Daniel Dennett, *Intuition Pumps and Other Tools for Thinking*
<hr>
> Everyone who operates in the public world and gets mail knows that a small percentage of the American population is completely out of its mind. It’s always been that way. The founding fathers probably received letters from people who believed King George was living in a barn down the road and spying on the local militia while disguised as a burro. The difference now, of course, is that the Internet and social media make them a lot more visible and noisy.

Gail Collins, in.  [NYT](http://nyti.ms/1zNVo4W)
<hr>
> The so-called "West Lothian Question" - the thorny issue of Westminster MPs sitting in Scotland, Wales or Northern Ireland being able to have a say over matters that affect only England - will finally be settled, once and for all, with the dissolution of the United Kingdom.

[The UK is now a failed state](http://bit.ly/1FXZQiM)
<hr>
> The nature of reality that spills forth from Einstein’s physics is so much more startling than the simplistic, undergraduate-beloved shibboleth: everything is relative to subjective points of view. In Einstein’s physics, there is no passage of time, no unidirectional flow from the fixed past and toward the uncertain future. The temporal component of space-time is as static as its spatial components; physical time is as still as physical space. It is all laid out, the whole spread of events, in the tenseless four-dimensional space-time manifold.

Rebecca Goldstein quoted in [Brain Pickings](http://bit.ly/1H2BUal)
<hr>
> There has been some realization that collecting and connecting dots when everything and anything looks like a dot is less than illuminating.

Amy Davidson in the [New Yorker](http://nyr.kr/1PCoV3B)
<hr>
> What was really lethal was the interaction between size and complexity. Financial institutions had become chimeras: part bank, part hedge fund, part insurance company, and so on. This complexity let them evade regulation, yet be rescued from the consequences when their bets went bad. And bankers’ ability to have it both ways helped set America up for disaster.

[Krugman](http://nyti.ms/1ASjuqB)
<hr>
> I weary of scholars neighing against Ahab, who is magnificent in his heroism. Would they have him hunt for more blubber? His chase has Job’s Leviathan in view, a quarry representing Yahweh’s sanctified tyranny of nature over man.

Harold Bloom,  *The Daemon Knows: Literary Greatness and the American Sublime*
<hr>
> It is not too much to say that no formula which expresses clearly the thought of one generation, can convey the same meaning to the generation which follows.

Brooke Foss Westcott, D.D., D.C.L
Bishop of Durham, Late Regius Professor of Divinity, Cambridge, and Canon of Westminster
<hr>
> A reconciliation between the two conflicting requirements is effected by a resort to make-believe.

Thorstein Veblen, *Theory of the Leisure Class*
<hr>
> Christof Koch, at the Allen Institute, likens Deisseroth to Galileo, whose early improvements of the telescope afforded a huge advance in our understanding of the cosmos. Even so, like Galileo’s telescope, which opened up the immensity of space, Deisseroth’s technologies have helped reveal how little we know about the brain—what Koch calls “by far the most complex piece of organized matter in the known universe.”

[The Optogenetics Breakthrough - The New Yorker](http://nyr.kr/1JFozaD)
<hr>
> We were, however, doomed, and knew it. The constitution of parents and children may, like the British one, be unwritten, but, as the Brits point out, that doesn’t make it less enforceable or authoritative. The unwritten compact that governs family life says somewhere that children who have waited long enough for a dog and want one badly enough have a right to have one. I felt as the Queen must at meeting an unpleasant Socialist Prime Minister: it isn’t what you wanted, but it’s your constitutional duty to welcome, and pretend.

Adam Gopnik in [New Yorker](http://nyr.kr/1EF4e0W)
<hr>
> The way the public hears about conservation issues is nearly always in the mode of ‘Beloved Animal Threatened With Extinction’.

Stewart Brand, [Aeon](http://bit.ly/1FrZrVv)
<hr>
>  It is one of the key features of early 21st century political campaigns and political life in general that every political figure requires a chorus of dedicated partisans who lay down the equivalent of covering fire in their leader's defense. Sometimes this happens with a political figure who attracts intense loyalty. But that's seldom required. Partisans on both sides of the political divide will generally rush to the defense of almost any political figure on their team, even if the person isn't terribly well liked or even if they're getting grief for something that is pretty hard to defend.

[TPM](http://bit.ly/1HjhXRR)
<hr>
> Galatea never does quite like Pygmalion: his relation to her is too godlike to be altogether agreeable.

G.B. Shaw, *Pygmalian*
<hr>
> When we treat each other as intentional systems, we are similarly finessing our ignorance of the details of the processes going on in each other’s skulls (and in our own!) and relying, unconsciously, on the fact that to a remarkably good first approximation, people are rational.

Daniel Dennett, *Intuition Pumps and Other Tools for Thinking*
<hr>
> The potentates of this world are sufficiently apt to consider themselves as possessed of an inherent superiority which gives them a right to govern and makes mankind their own; and this infatuation is almost every where fostered in them by the creeping sycophants about them and the language of flattery which they are continually hearing.

*A Discourse on the Love of our Country* by Richard Price, delivered on Nov. 4, 1789, at the Meeting-House in the Old Jewry, to the Society for Commemorating the Revolution in Great Britain
<hr>
> Plato, Lucretius, Pascal, Hegel, Dostoevsky, Nietzsche, Ibsen, Proust are, in varying degrees, hedgehogs; Herodotus, Aristotle, Montaigne, Erasmus, Molière, Goethe, Pushkin, Balzac, Joyce are foxes.

Isaiah Berlin, *The Hedgehog and the Fox*
<hr>
> The idea that objective observation can be performed only by an observer totally free of subjectivity involves an ideal of inhuman purity which we now recognise as being, fortunately, unattainable.

Ursula K. Le Guin, *The Wave in the Mind*
<hr>
> And I thought he was foolish, this man in his seventies, who had no idea what you must do. But the fanaticism of my twenties shocks me now. As I feared it would.

Annie Dillard, *The Writing Life*
<hr>
> With great force he argues that only those orders or decisions issued by the commanders now seem particularly crucial (and are concentrated upon by historians) which happened to coincide with what later actually occurred; whereas a great many other exactly similar, perfectly good orders and decisions, which seemed no less crucial and vital to those who were issuing them at the time, are forgotten because, having been foiled by unfavourable turns of events, they were not, because they could not be, carried out, and for this reason now seem historically unimportant.

Isaiah Berlin, *The Hedgehog and the Fox*
<hr>
> And yet, instead of exclaiming “Send this inconceivable Satanist to the stake,” the respectable newspapers pith me by announcing “another book by this brilliant and thoughtful writer.” And the ordinary citizen, knowing that an author who is well spoken of by a respectable newspaper must be all right, reads me, as he reads Micah, with undisturbed edification from his own point of view. It is narrated that in the eighteen-seventies an old lady, a very devout Methodist, moved from Colchester to a house in the neighborhood of the City Road, in London, where, mistaking the Hall of Science for a chapel, she sat at the feet of Charles Bradlaug for many years, entranced by his eloquence, without questioning his orthodoxy or moulting a feather of her faith. I fear I shall be defrauded of my just martyrdom in the same way.

G.B. Shaw, *Preface to Man and Superman*
<hr>
> Read other people’s myths, not those of your own religion, because you tend to interpret your own religion in terms of facts— but if you read the other ones, you begin to get the message.

Joseph Campbell in conversation with Bill Moyers, *The Power of Myth*
<hr>
> Whatever shape Liston was in, he did turn out to be child-friendly, fulfilling Michael Feldman’s wish for him to visit his school. “I was the first Jewish student in the school, and for show-and-tell, I brought a black former heavyweight champion,” he said.

[NYT](http://nyti.ms/1EhNnAC)
<hr>
> the great French gift for producing courteous children is more than met by the rage and misery that most French children feel about the discipline necessary to produce the manners (it’s why they riot at eighteen);

Jeffrey Toobin in the [New Yorker](http://nyr.kr/1LgwkV1)
<hr>
> You know, we have a tremendous amount of information about this subject, but there is a place where the information stops.

Joseph Campbell in conversation with Bill Moyers, *The Power of Myth*
<hr>
> We have been dreaming of robots since Homer.

Daniel Mendholsohn in[NYRB](http://bit.ly/1Gx9MAg)
<hr>
> Doing his utmost, deploying all his energy, a young man setting out from zero can wind up after ten years somewhere below where he started. Today, talent needs the kind of luck that favors the incompetent; in fact, if a skilled man rejects the vile arrangements that bring success to rampant mediocrity, he will never get on at all.

Balzac, *Z. Marcas* (tr. Linda Asher, Carol Cosman and Jordan Stump)
<hr>
> This violent contradiction between the data of experience, from which he could not liberate himself, and which, of course, all his life he knew alone to be real, and his deeply metaphysical belief in the existence of a system to which they must belong, whether they appear to do so or not, this conflict between instinctive judgement and theoretical conviction – between his gifts and his opinions – mirrors the unresolved conflict between the reality of the moral life, with its sense of responsibility, joys, sorrows, sense of guilt and sense of achievement – all of which is nevertheless illusion – and the laws which govern everything, although we cannot know more than a negligible portion of them – so that all scientists and historians who say that they do know them and are guided by them are lying and deceiving – but which nevertheless alone are real.

Isaiah Berlin, *The Hedgehog and the Fox*
<hr>
> These days, political scientists, evolutionary biologists, and even government regulators are obliged to grasp best-response equilibria and other aspects of game theory. Whenever a government agency is considering a new rule—a set of capital requirements for banks, say, or an environmental regulation—one of the first questions it needs to ask is whether obeying the rules leads to a Nash equilibrium. If it doesn’t, the new policy measure is likely to prove a failure, because those affected will seek a way around it.

John Cassidy in [New Yorker](http://nyr.kr/1HLLeVC)
<hr>
> I’m glad for my songs to be honored like this. But you know, they didn’t get here by themselves. It’s been a long road and it’s taken a lot of doing. These songs of mine, they’re like mystery stories, the kind that Shakespeare saw when he was growing up. I think you could trace what I do back that far. They were on the fringes then, and I think they’re on the fringes now. And they sound like they’ve been on the hard ground.

[Dylan](http://www.latimes.com/entertainment/music/posts/la-et-ms-grammys-2015-transcript-of-bob-dylans-musicares-person-of-year-speech-20150207-story.html)
<hr>
> I say to the cast, “Henry didn’t know he was going to have six wives. Each time he thought, here’s the girl for me.” People smile, but they grasp the essential thing. The characters don’t know their own fates. They can’t learn a lesson from themselves, and draw a moral. We have scripts, but they don’t. They are trapped in 50 years of improvisation, called life.

Hilary Mantel in [NYT](http://nyti.ms/1Rr6tO6)
<hr>
>  So numerous indeed and so powerful are the causes which serve to give a false bias to the judgment, that we, upon many occasions, see wise and good men on the wrong as well as on the right side of questions of the first magnitude to society. This circumstance, if duly attended to, would furnish a lesson of moderation to those who are ever so much persuaded of their being in the right in any controversy.

Hamilton, *Federalist № 1*
<hr>
> Far from marking the "end of imperialism", what we are witnessing today, a century after the implosion of the Ottoman empire, is its resurgence. In this new scramble for the Middle East, we are witnessing the petty sultans of the region's crumbling states trying to hold on to their micro-empires; non-state armed groups trying to usurp them; Iran and the emerging powers of the Gulf seeking to expand their spheres of influence; and the US' long-standing hegemony being challenged by the new-old kid on the block, Russia, and newcomer China.

Khaled Diab in [Al Jazeera](http://bit.ly/1FNEtPx)
<hr>
> And, it seemed, he never elaborated elsewhere. After his death, his son Samuel published a new edition of Arithmetica that included all of the notes that Fermat had made in its margins. These observations, typically stated without proof, posed an irresistible challenge. Within a few years, readers had confirmed every one—except the statement about higher-dimension Pythagorean triples. It was the “last” unsubstantiated claim.

Peter Brown in [Nautilus](http://bit.ly/1dbkC2)
<hr>
> when you think about what people are actually undergoing in our civilization, you realize it’s a very grim thing to be a modern human being.

Joseph Campbell in conversation with Bill Moyers, *The Power of Myth*
<hr>
> Betting on the flip of a coin involves high risk, but the potential outcomes and probability are known. “Uncertainty is when you can’t know all the outcomes or the probability with which each potential outcome will occur,” he said. “This is deep uncertainty.”

Yanis Varoufakis, quoted in [NYT](http://nyti.ms/1HQrlaA)
<hr>
> Only in the realm of mishearing — at least, my mishearings — can a biography of cancer become a biography of Cantor (one of my favorite mathematicians), tarot cards turn into pteropods, a grocery bag into a poetry bag, all-or-noneness into oral numbness, a porch into a Porsche, and a mere mention of Christmas Eve a command to “Kiss my feet."

Oliver Sachs in [NYT](http://nyti.ms/1G1AzCI)
<hr>
> He was bouncing down the lane as if jumping from one trampoline to another, and no one was going to catch him.

Joe Drape in [NYT](http://nyti.ms/1Jx3l2f)
<hr>
> The book sets its sights high from the very first words. “O, what a world of unseen visions and heard silences, this insubstantial country of the mind!” Jaynes begins. “A secret theater of speechless monologue and prevenient counsel, an invisible mansion of all moods, musings, and mysteries, an infinite resort of disappointments and discoveries.”

Julian Jaymes, quoted by Veronique Greenwood in [Nautilus](http://bit.ly/1G7xgdi)
<hr>
> Here indeed is a major difference between people and ants: where we send our young men to war, ants send their old ladies. No moral lesson there, unless you are looking for a less expensive form of elder care.

E.O. Wilson, *The Meaning of Human Existence*
<hr>
> These are the clover days. The light of June is not golden but silvery, not a torrid but somewhat temperate heat. See it reflected from the bent grass and the under sides of leaves.

Thoreau, *Journal* Jun. 19, 1854
<hr>
> “Life passes into pages if it passes into anything,” he once wrote. It has nowhere else to go. The pages, at least, will have some permanence.

James Satler, quoted in [New Yorker](http://nyr.kr/1dbxQfE)
<hr>
> We now have roses on the land and lilies on the water,— both land and water have done their best,— now just after the longest day. Nature says, “You behold the utmost I can do.” And the young women carry their finest roses on the other hand. Roses and lilies. The floral days. The highest, intensest color belongs to the land, the purest, perchance, to the water.

Thoreau, *Journal* Jun. 26, 1854
<hr>
> In my experience nothing is so opposed to poetry— not crime— as business. It is a negation of life.

Thoreau, *Journal* Jun. 29, 1854
<hr>
> Nature is reported not by him who goes forth consciously as an observer, but in the fullness of life. To such a one she rushes to make her report.

Thoreau, *Journal*, Jul 3, 1854
<hr>
> Barricelli saw his computer organisms as a blueprint of life—on this planet and any others. “The question whether one type of symbio-organism is developed in the memory of a digital computer while another type is developed in a chemical laboratory or by a natural process on some planet or satellite does not add anything fundamental to this difference,” he wrote. A month after Barricelli began his experiments on the IAS machine, Crick and Watson announced the shape of DNA as a double helix. But learning about the shape of biological life didn’t put a dent in Barricelli’s conviction that he had captured the mechanics of life on a computer. Let Watson and Crick call DNA a double helix. Barricelli called it “molecule-shaped numbers.”

Robert Hackett in [Nautilus](http://bit.ly/1ChAjl8)
<hr>
> To understand the story of the Three Little Pigs, one must comprehend what each of the characters knows. For a machine to replicate this understanding, it needs to recognize these individual sets of characters’ knowledge. It needs a single set to represent the pig’s knowledge of the world, another for the wolf’s, along with a representation of the mental state the wolf is trying to get the pig into — the deception. These contexts can be layered infinitely, and Fahlman is building a system that contains them.

Rachel Wilkinson in [Narratively](http://nxt.fm/1dKyq4s)
<hr>
 > The youth gets together his materials to build a bridge to the moon, or perchance a palace or temple on the earth, and at length the middle-aged man concludes to build a wood-shed with them.

Thoreau, *Journal*, Jul. 15, 1854
<hr>
> When the Almighty himself condescends to address mankind in their own language, his meaning, luminous as it must be, is rendered dim and doubtful by the cloudy medium through which it is communicated.

Madison, *Federalist* 37
<hr>
> After midsummer we have a belated feeling as if we had all been idlers, and are forward to see in each sight and hear in each sound some presage of the fall, just as in middle age man anticipates the end of life.

Thoreau, *Journal*, Jul. 30, 1854
<hr>
> I only know myself as a human entity, the scene, so to speak, of thoughts and affections, and am sensible of a certain doubleness by which I can stand as remote from myself as from another. However intense my experience, I am conscious of the presence and criticism of a part of me which, as it were, is not a part of me, but spectator, sharing no experience, but taking note of it, and that is no more I than it is you. When the play—it may be the tragedy of life—is over, the spectator goes his way. It was a kind of fiction, a work of the imagination only, so far as he was concerned.

Thoreau, *Journal* Aug. 8, 1854
<hr>
> Nothing humanizes us like aporia –that state of intense puzzlement in which we find ourselves when our certainties fall to pieces; when suddenly we get caught in an impasse, at a loss to explain what our eyes can see, our fingers can touch, our ears can hear. At those rare moments, as our reason valiantly struggles to fathom what the senses are reporting, our aporia humbles us and readies the prepared mind for previously unbearable truths. And when the aporia casts its net far and wide to ensnare the whole of humanity, we know we are at a very special moment in history. September 2008 was just such a moment.

Yanis Varoufakis, *The Global Minotaur*
<hr>
> The sound of the crickets gradually prevails more and more. I hear the year falling asleep.

Thoreau, *Journal*,  Aug. 21, 1854
<hr>
> The third charge against the House of Representatives is, that it will be taken from that class of citizens which will have least sympathy with the mass of the people, and be most likely to aim at an ambitious sacrifice of the many to the aggrandizement of the few.

*Federalist*, LVII
<hr>

> There cannot be freedom of religion, safeguarded by the state, and intervention by the church or its agencies in the state's domain or dependency on its largesse... . The great condition of religious liberty is that it be maintained free from sustenance, as also from other interferences, by the state. For when it comes to rest upon that secular foundation it vanishes with the resting.

Justice Douglas, concurring in *Engle v. Vitale* (1962)
<hr>
> after I got into my sixties my faculty of respect atrophied.

 Ursula K. Le Guin, *The Wave in the Mind*
<hr>
> Neuroscience is the attempt to reverse engineer the brain.

Daniel Dennett, *Intuition Pumps and Other Tools for Thinking*
<hr>
> At the root of the practice may be a beautiful, humane sentiment; the utterance of it, especially in the poets, is, as a rule, of equivocal sincerity.

Jacob Burckhardt, *The Civilization of the Renaissance in Italy*
<hr>
> William James used to preach the “will to believe.” For my part, I should wish to preach the “will to doubt.” None of our beliefs are quite true; all have at least a penumbra of vagueness and error. The methods of increasing the degree of truth in our beliefs are well known; they consist in hearing all sides, trying to ascertain all the relevant facts, controlling our own bias by discussion with people who have the opposite bias, and cultivating a readiness to discard any hypothesis which has proved inadequate. These methods are practised in science, and have built up the body of scientific knowledge.

Bertrand Russell, *Freedom and Official Propaganda*
<hr>
> What is the good life? How to live? This ancient question of philosophy can remain academic to a man only until the day it comes at him in the form: How am *I* to live?

Zia Haider Rahman, *In the Light of What We Know*
<hr>
> the history of philosophy when boiled down consists mostly of failed models of the brain.

E.O. Wilson, *The Meaning of Human Existence*
<hr>
> “Try to sit down and write something like that. There’s a magic to that, and it’s not Siegfried and Roy kind of magic, you know? It’s a different kind of a penetrating magic. And, you know, I did it. I did it at one time. … You can’t do something forever. I did it once, and I can do other things now. But I can’t do that.”

Bob Dylan, quoted by David Remnick in the [New Yorker](http://bit.ly/1klifi6)
<hr>
> Every good work should have at least ten meanings.

Walter De Maria, quoted in Camille Paglia, [Glittering Images](http://amzn.to/1Zxklsk)
<hr>
> As Alexander Bessmertnykh, a former Soviet foreign minister, put it, “In real life, so it appears, events, our relations and our policies depend more on accidents, coincidences and acting on very little real knowledge of what is going on. We have been through so many crises in this way.”

Matt Peterson in [*The Atlantic*](https://goo.gl/DiAM5G)
<hr>
