<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.49" />


<title>Population and Ethnic Leverage in Control of U.S. Senate - Locus: Richard Careaga</title>
<meta property="og:title" content="Population and Ethnic Leverage in Control of U.S. Senate - Locus: Richard Careaga">



  



<link rel="stylesheet" type="text/css" href="https://cloud.typography.com/73384/6600392/css/fonts.css" />




<link href='//cdn.bootcss.com/highlight.js/9.11.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">

<link rel="stylesheet" href="/css/custom.css">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/technocrat">GitHub</a></li>
    
    <li><a href="https://technocrat.github.io/_book/">Portfolio</a></li>
    
    <li><a href="/quotes/">Quotes</a></li>
    
    <li><a href="https://linkedin.com/in/richardcareaga">LinkedIn</a></li>
    
    <li><a href="https://twitter.com/technocrat">Twitter</a></li>
    
    <li><a href="/employment/">Employment</a></li>
    
    <li><a href="https://www.r-bloggers.com">RBloggers</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">18 min read</span>
    

    <h1 class="article-title">Population and Ethnic Leverage in Control of U.S. Senate</h1>



    
    <span class="article-date">2018/11/10</span>
    

    
    <br>
      
    

    <div class="article-content">
      <script src="/rmarkdown-libs/kePrint/kePrint.js"></script>


<pre><code>## Please note: Alaska and Hawaii are being shifted and are not to scale.</code></pre>
<pre><code>## Getting data from the 2012-2016 5-year ACS</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   NAME = col_character(),
##   Q22018_GDP = col_double()
## )</code></pre>
<div id="population-among-states-was-unevenly-distributed-in-the-first-census" class="section level1">
<h1>Population Among States Was Unevenly Distributed in the First Census</h1>
<div class="figure">
<img src="https://www.census.gov/history/img/1790-b.jpg" alt="1790 Population Density" />
<p class="caption">1790 Population Density</p>
</div>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:1790">Table 1: </span>States in 1790
</caption>
<thead>
<tr>
<th style="text-align:left;">
State
</th>
<th style="text-align:right;">
Population
</th>
<th style="text-align:right;">
Proportion_US
</th>
<th style="text-align:right;">
Cumulative
</th>
<th style="text-align:right;">
Voters
</th>
<th style="text-align:right;">
Proportion_Instate
</th>
<th style="text-align:right;">
Cumulative_US
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Delaware
</td>
<td style="text-align:right;">
59,094
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
11,783
</td>
<td style="text-align:right;">
0.20
</td>
<td style="text-align:right;">
0.02
</td>
</tr>
<tr>
<td style="text-align:left;">
Rhode Island
</td>
<td style="text-align:right;">
68,825
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
0.04
</td>
<td style="text-align:right;">
16,019
</td>
<td style="text-align:right;">
0.23
</td>
<td style="text-align:right;">
0.04
</td>
</tr>
<tr>
<td style="text-align:left;">
Georgia
</td>
<td style="text-align:right;">
82,548
</td>
<td style="text-align:right;">
0.02
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:right;">
13,103
</td>
<td style="text-align:right;">
0.16
</td>
<td style="text-align:right;">
0.05
</td>
</tr>
<tr>
<td style="text-align:left;">
New Hampshire
</td>
<td style="text-align:right;">
141,885
</td>
<td style="text-align:right;">
0.04
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
36,086
</td>
<td style="text-align:right;">
0.25
</td>
<td style="text-align:right;">
0.10
</td>
</tr>
<tr>
<td style="text-align:left;">
New Jersey
</td>
<td style="text-align:right;">
184,139
</td>
<td style="text-align:right;">
0.05
</td>
<td style="text-align:right;">
0.15
</td>
<td style="text-align:right;">
45,251
</td>
<td style="text-align:right;">
0.25
</td>
<td style="text-align:right;">
0.16
</td>
</tr>
<tr>
<td style="text-align:left;">
Connecticut
</td>
<td style="text-align:right;">
237,946
</td>
<td style="text-align:right;">
0.06
</td>
<td style="text-align:right;">
0.21
</td>
<td style="text-align:right;">
60,523
</td>
<td style="text-align:right;">
0.25
</td>
<td style="text-align:right;">
0.23
</td>
</tr>
<tr>
<td style="text-align:left;">
South Carolina
</td>
<td style="text-align:right;">
249,073
</td>
<td style="text-align:right;">
0.07
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:right;">
35,576
</td>
<td style="text-align:right;">
0.14
</td>
<td style="text-align:right;">
0.28
</td>
</tr>
<tr>
<td style="text-align:left;">
Maryland
</td>
<td style="text-align:right;">
319,728
</td>
<td style="text-align:right;">
0.08
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
55,915
</td>
<td style="text-align:right;">
0.17
</td>
<td style="text-align:right;">
0.35
</td>
</tr>
<tr>
<td style="text-align:left;">
New York
</td>
<td style="text-align:right;">
340,120
</td>
<td style="text-align:right;">
0.09
</td>
<td style="text-align:right;">
0.45
</td>
<td style="text-align:right;">
83,700
</td>
<td style="text-align:right;">
0.25
</td>
<td style="text-align:right;">
0.46
</td>
</tr>
<tr>
<td style="text-align:left;">
North Carolina
</td>
<td style="text-align:right;">
393,751
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:right;">
69,988
</td>
<td style="text-align:right;">
0.18
</td>
<td style="text-align:right;">
0.55
</td>
</tr>
<tr>
<td style="text-align:left;">
Pennsylvania
</td>
<td style="text-align:right;">
434,373
</td>
<td style="text-align:right;">
0.11
</td>
<td style="text-align:right;">
0.66
</td>
<td style="text-align:right;">
110,788
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0.69
</td>
</tr>
<tr>
<td style="text-align:left;">
Massachusetts
</td>
<td style="text-align:right;">
475,327
</td>
<td style="text-align:right;">
0.12
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
119,837
</td>
<td style="text-align:right;">
0.25
</td>
<td style="text-align:right;">
0.84
</td>
</tr>
<tr>
<td style="text-align:left;">
Virginia
</td>
<td style="text-align:right;">
821,287
</td>
<td style="text-align:right;">
0.22
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
126,090
</td>
<td style="text-align:right;">
0.15
</td>
<td style="text-align:right;">
1.00
</td>
</tr>
</tbody>
</table>
<p>Each state, then as now, elects two Senators, whether it accounts for 2% of the national population, in the case of Delaware, or 22%, for Virginia.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> Within each state, those potentially eligible to vote represented around 15% of the in-state population, in the slave holding states, and around 25% in the states with low slave population.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> The fundamental feature of the composition of the Senate, equal representation of <strong>states</strong> rather than population, or even voters, was an integral part of the design of the Constitution.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>.</p>
<p>The Senate is a non-democratic institution when considered at the national level. One historian virtually makes the case that the Senate represented nothing other than itself until 1957.<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a></p>
<p><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/colonial_map-1.png" width="672" /></p>
<p>Four states, Virginia, Massachusetts, Pennsylvania and North Carolina accounted for 55% of the national population residing in states but only 31% of the members of the Senate. Voting power was not evenly divided between the major slaveholding states, which included Virginia, North Carolina, Maryland, South Carolina and Georgia, and the remaining states.</p>
<p>The non-democratic nature of this arrangement is highlighted by the ratio of voters in Delaware, the smallest state in 1790, and Virginia, the largest. Given their relative number of voters, each Delaware vote had 10.7 times the influence on the factional composition of the Senate compared to each Virginia vote. Based on the total population, including the majority of dis-enfranchised, Delaware influence was slightly higher, 13.9 times that of Virginia.</p>
</div>
<div id="population-among-states-today-is-more-unevenly-distributed" class="section level1">
<h1>Population Among States Today is More Unevenly Distributed</h1>
<p>In 2017, with the addition of 37 new states, population has become more unevenly distributed among the states.</p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:pop_tabular_results)States ranked by population showing cumulative population share
</caption>
<thead>
<tr>
<th style="text-align:left;">
State
</th>
<th style="text-align:right;">
Population
</th>
<th style="text-align:right;">
Proportion
</th>
<th style="text-align:right;">
Cumulative
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Wyoming
</td>
<td style="text-align:right;">
579,315
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.002
</td>
</tr>
<tr>
<td style="text-align:left;">
Vermont
</td>
<td style="text-align:right;">
623,657
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.004
</td>
</tr>
<tr>
<td style="text-align:left;">
Alaska
</td>
<td style="text-align:right;">
739,795
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.006
</td>
</tr>
<tr>
<td style="text-align:left;">
North Dakota
</td>
<td style="text-align:right;">
755,393
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.008
</td>
</tr>
<tr>
<td style="text-align:left;">
South Dakota
</td>
<td style="text-align:right;">
869,666
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.011
</td>
</tr>
<tr>
<td style="text-align:left;">
Delaware
</td>
<td style="text-align:right;">
961,939
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.014
</td>
</tr>
<tr>
<td style="text-align:left;">
Montana
</td>
<td style="text-align:right;">
1,050,493
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.017
</td>
</tr>
<tr>
<td style="text-align:left;">
Rhode Island
</td>
<td style="text-align:right;">
1,059,639
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.020
</td>
</tr>
<tr>
<td style="text-align:left;">
Maine
</td>
<td style="text-align:right;">
1,335,907
</td>
<td style="text-align:right;">
0.004
</td>
<td style="text-align:right;">
0.024
</td>
</tr>
<tr>
<td style="text-align:left;">
New Hampshire
</td>
<td style="text-align:right;">
1,342,795
</td>
<td style="text-align:right;">
0.004
</td>
<td style="text-align:right;">
0.028
</td>
</tr>
<tr>
<td style="text-align:left;">
Hawaii
</td>
<td style="text-align:right;">
1,427,538
</td>
<td style="text-align:right;">
0.004
</td>
<td style="text-align:right;">
0.032
</td>
</tr>
<tr>
<td style="text-align:left;">
Idaho
</td>
<td style="text-align:right;">
1,716,943
</td>
<td style="text-align:right;">
0.005
</td>
<td style="text-align:right;">
0.037
</td>
</tr>
<tr>
<td style="text-align:left;">
West Virginia
</td>
<td style="text-align:right;">
1,815,857
</td>
<td style="text-align:right;">
0.006
</td>
<td style="text-align:right;">
0.043
</td>
</tr>
<tr>
<td style="text-align:left;">
Nebraska
</td>
<td style="text-align:right;">
1,920,076
</td>
<td style="text-align:right;">
0.006
</td>
<td style="text-align:right;">
0.049
</td>
</tr>
<tr>
<td style="text-align:left;">
New Mexico
</td>
<td style="text-align:right;">
2,088,070
</td>
<td style="text-align:right;">
0.006
</td>
<td style="text-align:right;">
0.055
</td>
</tr>
<tr>
<td style="text-align:left;">
Kansas
</td>
<td style="text-align:right;">
2,913,123
</td>
<td style="text-align:right;">
0.009
</td>
<td style="text-align:right;">
0.064
</td>
</tr>
<tr>
<td style="text-align:left;">
Mississippi
</td>
<td style="text-align:right;">
2,984,100
</td>
<td style="text-align:right;">
0.009
</td>
<td style="text-align:right;">
0.073
</td>
</tr>
<tr>
<td style="text-align:left;">
Nevada
</td>
<td style="text-align:right;">
2,998,039
</td>
<td style="text-align:right;">
0.009
</td>
<td style="text-align:right;">
0.082
</td>
</tr>
<tr>
<td style="text-align:left;">
Arkansas
</td>
<td style="text-align:right;">
3,004,279
</td>
<td style="text-align:right;">
0.009
</td>
<td style="text-align:right;">
0.091
</td>
</tr>
<tr>
<td style="text-align:left;">
Utah
</td>
<td style="text-align:right;">
3,101,833
</td>
<td style="text-align:right;">
0.010
</td>
<td style="text-align:right;">
0.101
</td>
</tr>
<tr>
<td style="text-align:left;">
Iowa
</td>
<td style="text-align:right;">
3,145,711
</td>
<td style="text-align:right;">
0.010
</td>
<td style="text-align:right;">
0.111
</td>
</tr>
<tr>
<td style="text-align:left;">
Connecticut
</td>
<td style="text-align:right;">
3,588,184
</td>
<td style="text-align:right;">
0.011
</td>
<td style="text-align:right;">
0.122
</td>
</tr>
<tr>
<td style="text-align:left;">
Oklahoma
</td>
<td style="text-align:right;">
3,930,864
</td>
<td style="text-align:right;">
0.012
</td>
<td style="text-align:right;">
0.134
</td>
</tr>
<tr>
<td style="text-align:left;">
Oregon
</td>
<td style="text-align:right;">
4,142,776
</td>
<td style="text-align:right;">
0.013
</td>
<td style="text-align:right;">
0.147
</td>
</tr>
<tr>
<td style="text-align:left;">
Kentucky
</td>
<td style="text-align:right;">
4,454,189
</td>
<td style="text-align:right;">
0.014
</td>
<td style="text-align:right;">
0.161
</td>
</tr>
<tr>
<td style="text-align:left;">
Louisiana
</td>
<td style="text-align:right;">
4,684,333
</td>
<td style="text-align:right;">
0.014
</td>
<td style="text-align:right;">
0.175
</td>
</tr>
<tr>
<td style="text-align:left;">
Alabama
</td>
<td style="text-align:right;">
4,874,747
</td>
<td style="text-align:right;">
0.015
</td>
<td style="text-align:right;">
0.190
</td>
</tr>
<tr>
<td style="text-align:left;">
South Carolina
</td>
<td style="text-align:right;">
5,024,369
</td>
<td style="text-align:right;">
0.015
</td>
<td style="text-align:right;">
0.205
</td>
</tr>
<tr>
<td style="text-align:left;">
Minnesota
</td>
<td style="text-align:right;">
5,576,606
</td>
<td style="text-align:right;">
0.017
</td>
<td style="text-align:right;">
0.222
</td>
</tr>
<tr>
<td style="text-align:left;">
Colorado
</td>
<td style="text-align:right;">
5,607,154
</td>
<td style="text-align:right;">
0.017
</td>
<td style="text-align:right;">
0.239
</td>
</tr>
<tr>
<td style="text-align:left;">
Wisconsin
</td>
<td style="text-align:right;">
5,795,483
</td>
<td style="text-align:right;">
0.018
</td>
<td style="text-align:right;">
0.257
</td>
</tr>
<tr>
<td style="text-align:left;">
Maryland
</td>
<td style="text-align:right;">
6,052,177
</td>
<td style="text-align:right;">
0.019
</td>
<td style="text-align:right;">
0.276
</td>
</tr>
<tr>
<td style="text-align:left;">
Missouri
</td>
<td style="text-align:right;">
6,113,532
</td>
<td style="text-align:right;">
0.019
</td>
<td style="text-align:right;">
0.295
</td>
</tr>
<tr>
<td style="text-align:left;">
Indiana
</td>
<td style="text-align:right;">
6,666,818
</td>
<td style="text-align:right;">
0.021
</td>
<td style="text-align:right;">
0.316
</td>
</tr>
<tr>
<td style="text-align:left;">
Tennessee
</td>
<td style="text-align:right;">
6,715,984
</td>
<td style="text-align:right;">
0.021
</td>
<td style="text-align:right;">
0.337
</td>
</tr>
<tr>
<td style="text-align:left;">
Massachusetts
</td>
<td style="text-align:right;">
6,859,819
</td>
<td style="text-align:right;">
0.021
</td>
<td style="text-align:right;">
0.358
</td>
</tr>
<tr>
<td style="text-align:left;">
Arizona
</td>
<td style="text-align:right;">
7,016,270
</td>
<td style="text-align:right;">
0.022
</td>
<td style="text-align:right;">
0.380
</td>
</tr>
<tr>
<td style="text-align:left;">
Washington
</td>
<td style="text-align:right;">
7,405,743
</td>
<td style="text-align:right;">
0.023
</td>
<td style="text-align:right;">
0.403
</td>
</tr>
<tr>
<td style="text-align:left;">
Virginia
</td>
<td style="text-align:right;">
8,470,020
</td>
<td style="text-align:right;">
0.026
</td>
<td style="text-align:right;">
0.429
</td>
</tr>
<tr>
<td style="text-align:left;">
New Jersey
</td>
<td style="text-align:right;">
9,005,644
</td>
<td style="text-align:right;">
0.028
</td>
<td style="text-align:right;">
0.457
</td>
</tr>
<tr>
<td style="text-align:left;">
Michigan
</td>
<td style="text-align:right;">
9,962,311
</td>
<td style="text-align:right;">
0.031
</td>
<td style="text-align:right;">
0.488
</td>
</tr>
<tr>
<td style="text-align:left;">
North Carolina
</td>
<td style="text-align:right;">
10,273,419
</td>
<td style="text-align:right;">
0.032
</td>
<td style="text-align:right;">
0.520
</td>
</tr>
<tr>
<td style="text-align:left;">
Georgia
</td>
<td style="text-align:right;">
10,429,379
</td>
<td style="text-align:right;">
0.032
</td>
<td style="text-align:right;">
0.552
</td>
</tr>
<tr>
<td style="text-align:left;">
Ohio
</td>
<td style="text-align:right;">
11,658,609
</td>
<td style="text-align:right;">
0.036
</td>
<td style="text-align:right;">
0.588
</td>
</tr>
<tr>
<td style="text-align:left;">
Illinois
</td>
<td style="text-align:right;">
12,802,023
</td>
<td style="text-align:right;">
0.039
</td>
<td style="text-align:right;">
0.627
</td>
</tr>
<tr>
<td style="text-align:left;">
Pennsylvania
</td>
<td style="text-align:right;">
12,805,537
</td>
<td style="text-align:right;">
0.039
</td>
<td style="text-align:right;">
0.666
</td>
</tr>
<tr>
<td style="text-align:left;">
New York
</td>
<td style="text-align:right;">
19,849,399
</td>
<td style="text-align:right;">
0.061
</td>
<td style="text-align:right;">
0.727
</td>
</tr>
<tr>
<td style="text-align:left;">
Florida
</td>
<td style="text-align:right;">
20,984,400
</td>
<td style="text-align:right;">
0.065
</td>
<td style="text-align:right;">
0.792
</td>
</tr>
<tr>
<td style="text-align:left;">
Texas
</td>
<td style="text-align:right;">
28,304,596
</td>
<td style="text-align:right;">
0.087
</td>
<td style="text-align:right;">
0.879
</td>
</tr>
<tr>
<td style="text-align:left;">
California
</td>
<td style="text-align:right;">
39,536,653
</td>
<td style="text-align:right;">
0.122
</td>
<td style="text-align:right;">
1.001
</td>
</tr>
</tbody>
</table>
<p>In 1790, the smallest state, Delaware, had approximately 2% of the population of the United States. In 2017, it must join with Rhode Island, Vermont (which joined the United States only in 1791) and six western states (Wyoming, Alaska, North Dakota, South Dakota, and Montana) to reach 2%.</p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:lower_two_pct)States comprising 2% in total of the 2017 United States population
</caption>
<thead>
<tr>
<th style="text-align:left;">
State
</th>
<th style="text-align:right;">
Population
</th>
<th style="text-align:right;">
Proportion
</th>
<th style="text-align:right;">
Cumulative
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Wyoming
</td>
<td style="text-align:right;">
579,315
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.002
</td>
</tr>
<tr>
<td style="text-align:left;">
Vermont
</td>
<td style="text-align:right;">
623,657
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.004
</td>
</tr>
<tr>
<td style="text-align:left;">
Alaska
</td>
<td style="text-align:right;">
739,795
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.006
</td>
</tr>
<tr>
<td style="text-align:left;">
North Dakota
</td>
<td style="text-align:right;">
755,393
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.008
</td>
</tr>
<tr>
<td style="text-align:left;">
South Dakota
</td>
<td style="text-align:right;">
869,666
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.011
</td>
</tr>
<tr>
<td style="text-align:left;">
Delaware
</td>
<td style="text-align:right;">
961,939
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.014
</td>
</tr>
<tr>
<td style="text-align:left;">
Montana
</td>
<td style="text-align:right;">
1,050,493
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.017
</td>
</tr>
<tr>
<td style="text-align:left;">
Rhode Island
</td>
<td style="text-align:right;">
1,059,639
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.020
</td>
</tr>
</tbody>
</table>
<p>While lowest-population Delaware enjoyed a relative voting power 13.9 times that of Virginia, the most populous state in 1790, the relative adjantage of the eight states comprising today’s cumulative 2% of the population, relative to 2017’s most populuous state, California, has declined to 5.95. However, today’s lowest population state, Wyoming, has a population based relative advantage multiple of 68.2 over California. Simply put, it takes 68 California residents to have the same influence on the selection of a Senator as 1 Wyoming resident.</p>
<p>The 20 states with populations of less than approximately 3.6 million, taken together, have the approximately the same population as California. It takes 20 California residents to have the same influence on the selection of a single Senator as 1 resident of those 20 states taken as a whole.</p>
<p>Just nine states: California, Texas, Florida, New York, Pennslyvania, Illinois, Ohio, Georgia and North Carolina comprise the majority of the population of the United States, approximately 52%. The remaining 48% of the population live in states with populations less than 10 million.</p>
<p>There are 26 states, each representing less than approximately 1.5% of the national population, which together account for a decided minority, 17.5%, of the national population.</p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:lo_states)States with populations less than 1.5% of the national total
</caption>
<thead>
<tr>
<th style="text-align:left;">
State
</th>
<th style="text-align:right;">
Population
</th>
<th style="text-align:right;">
Proportion
</th>
<th style="text-align:right;">
Cumulative
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Wyoming
</td>
<td style="text-align:right;">
579,315
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.002
</td>
</tr>
<tr>
<td style="text-align:left;">
Vermont
</td>
<td style="text-align:right;">
623,657
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.004
</td>
</tr>
<tr>
<td style="text-align:left;">
Alaska
</td>
<td style="text-align:right;">
739,795
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.006
</td>
</tr>
<tr>
<td style="text-align:left;">
North Dakota
</td>
<td style="text-align:right;">
755,393
</td>
<td style="text-align:right;">
0.002
</td>
<td style="text-align:right;">
0.008
</td>
</tr>
<tr>
<td style="text-align:left;">
South Dakota
</td>
<td style="text-align:right;">
869,666
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.011
</td>
</tr>
<tr>
<td style="text-align:left;">
Delaware
</td>
<td style="text-align:right;">
961,939
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.014
</td>
</tr>
<tr>
<td style="text-align:left;">
Montana
</td>
<td style="text-align:right;">
1,050,493
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.017
</td>
</tr>
<tr>
<td style="text-align:left;">
Rhode Island
</td>
<td style="text-align:right;">
1,059,639
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.020
</td>
</tr>
<tr>
<td style="text-align:left;">
Maine
</td>
<td style="text-align:right;">
1,335,907
</td>
<td style="text-align:right;">
0.004
</td>
<td style="text-align:right;">
0.024
</td>
</tr>
<tr>
<td style="text-align:left;">
New Hampshire
</td>
<td style="text-align:right;">
1,342,795
</td>
<td style="text-align:right;">
0.004
</td>
<td style="text-align:right;">
0.028
</td>
</tr>
<tr>
<td style="text-align:left;">
Hawaii
</td>
<td style="text-align:right;">
1,427,538
</td>
<td style="text-align:right;">
0.004
</td>
<td style="text-align:right;">
0.032
</td>
</tr>
<tr>
<td style="text-align:left;">
Idaho
</td>
<td style="text-align:right;">
1,716,943
</td>
<td style="text-align:right;">
0.005
</td>
<td style="text-align:right;">
0.037
</td>
</tr>
<tr>
<td style="text-align:left;">
West Virginia
</td>
<td style="text-align:right;">
1,815,857
</td>
<td style="text-align:right;">
0.006
</td>
<td style="text-align:right;">
0.043
</td>
</tr>
<tr>
<td style="text-align:left;">
Nebraska
</td>
<td style="text-align:right;">
1,920,076
</td>
<td style="text-align:right;">
0.006
</td>
<td style="text-align:right;">
0.049
</td>
</tr>
<tr>
<td style="text-align:left;">
New Mexico
</td>
<td style="text-align:right;">
2,088,070
</td>
<td style="text-align:right;">
0.006
</td>
<td style="text-align:right;">
0.055
</td>
</tr>
<tr>
<td style="text-align:left;">
Kansas
</td>
<td style="text-align:right;">
2,913,123
</td>
<td style="text-align:right;">
0.009
</td>
<td style="text-align:right;">
0.064
</td>
</tr>
<tr>
<td style="text-align:left;">
Mississippi
</td>
<td style="text-align:right;">
2,984,100
</td>
<td style="text-align:right;">
0.009
</td>
<td style="text-align:right;">
0.073
</td>
</tr>
<tr>
<td style="text-align:left;">
Nevada
</td>
<td style="text-align:right;">
2,998,039
</td>
<td style="text-align:right;">
0.009
</td>
<td style="text-align:right;">
0.082
</td>
</tr>
<tr>
<td style="text-align:left;">
Arkansas
</td>
<td style="text-align:right;">
3,004,279
</td>
<td style="text-align:right;">
0.009
</td>
<td style="text-align:right;">
0.091
</td>
</tr>
<tr>
<td style="text-align:left;">
Utah
</td>
<td style="text-align:right;">
3,101,833
</td>
<td style="text-align:right;">
0.010
</td>
<td style="text-align:right;">
0.101
</td>
</tr>
<tr>
<td style="text-align:left;">
Iowa
</td>
<td style="text-align:right;">
3,145,711
</td>
<td style="text-align:right;">
0.010
</td>
<td style="text-align:right;">
0.111
</td>
</tr>
<tr>
<td style="text-align:left;">
Connecticut
</td>
<td style="text-align:right;">
3,588,184
</td>
<td style="text-align:right;">
0.011
</td>
<td style="text-align:right;">
0.122
</td>
</tr>
<tr>
<td style="text-align:left;">
Oklahoma
</td>
<td style="text-align:right;">
3,930,864
</td>
<td style="text-align:right;">
0.012
</td>
<td style="text-align:right;">
0.134
</td>
</tr>
<tr>
<td style="text-align:left;">
Oregon
</td>
<td style="text-align:right;">
4,142,776
</td>
<td style="text-align:right;">
0.013
</td>
<td style="text-align:right;">
0.147
</td>
</tr>
<tr>
<td style="text-align:left;">
Kentucky
</td>
<td style="text-align:right;">
4,454,189
</td>
<td style="text-align:right;">
0.014
</td>
<td style="text-align:right;">
0.161
</td>
</tr>
<tr>
<td style="text-align:left;">
Louisiana
</td>
<td style="text-align:right;">
4,684,333
</td>
<td style="text-align:right;">
0.014
</td>
<td style="text-align:right;">
0.175
</td>
</tr>
</tbody>
</table>
<p>There are 13 states, each representing less than approximately 3% national population, collectively, 26.6%, of the of the national population.</p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:mid_states)States with populations greater than 1.5% but less than 3% of the national total
</caption>
<thead>
<tr>
<th style="text-align:left;">
State
</th>
<th style="text-align:right;">
Population
</th>
<th style="text-align:right;">
Proportion
</th>
<th style="text-align:right;">
Cumulative
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Minnesota
</td>
<td style="text-align:right;">
5,576,606
</td>
<td style="text-align:right;">
0.017
</td>
<td style="text-align:right;">
0.222
</td>
</tr>
<tr>
<td style="text-align:left;">
Colorado
</td>
<td style="text-align:right;">
5,607,154
</td>
<td style="text-align:right;">
0.017
</td>
<td style="text-align:right;">
0.239
</td>
</tr>
<tr>
<td style="text-align:left;">
Wisconsin
</td>
<td style="text-align:right;">
5,795,483
</td>
<td style="text-align:right;">
0.018
</td>
<td style="text-align:right;">
0.257
</td>
</tr>
<tr>
<td style="text-align:left;">
Maryland
</td>
<td style="text-align:right;">
6,052,177
</td>
<td style="text-align:right;">
0.019
</td>
<td style="text-align:right;">
0.276
</td>
</tr>
<tr>
<td style="text-align:left;">
Missouri
</td>
<td style="text-align:right;">
6,113,532
</td>
<td style="text-align:right;">
0.019
</td>
<td style="text-align:right;">
0.295
</td>
</tr>
<tr>
<td style="text-align:left;">
Indiana
</td>
<td style="text-align:right;">
6,666,818
</td>
<td style="text-align:right;">
0.021
</td>
<td style="text-align:right;">
0.316
</td>
</tr>
<tr>
<td style="text-align:left;">
Tennessee
</td>
<td style="text-align:right;">
6,715,984
</td>
<td style="text-align:right;">
0.021
</td>
<td style="text-align:right;">
0.337
</td>
</tr>
<tr>
<td style="text-align:left;">
Massachusetts
</td>
<td style="text-align:right;">
6,859,819
</td>
<td style="text-align:right;">
0.021
</td>
<td style="text-align:right;">
0.358
</td>
</tr>
<tr>
<td style="text-align:left;">
Arizona
</td>
<td style="text-align:right;">
7,016,270
</td>
<td style="text-align:right;">
0.022
</td>
<td style="text-align:right;">
0.380
</td>
</tr>
<tr>
<td style="text-align:left;">
Washington
</td>
<td style="text-align:right;">
7,405,743
</td>
<td style="text-align:right;">
0.023
</td>
<td style="text-align:right;">
0.403
</td>
</tr>
<tr>
<td style="text-align:left;">
Virginia
</td>
<td style="text-align:right;">
8,470,020
</td>
<td style="text-align:right;">
0.026
</td>
<td style="text-align:right;">
0.429
</td>
</tr>
<tr>
<td style="text-align:left;">
New Jersey
</td>
<td style="text-align:right;">
9,005,644
</td>
<td style="text-align:right;">
0.028
</td>
<td style="text-align:right;">
0.457
</td>
</tr>
<tr>
<td style="text-align:left;">
Michigan
</td>
<td style="text-align:right;">
9,962,311
</td>
<td style="text-align:right;">
0.031
</td>
<td style="text-align:right;">
0.488
</td>
</tr>
</tbody>
</table>
<p>There are 9 states, each representing more than approximately 3% national population, which together account for 52%, the majority, of the national population.</p>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:hi_states)States with populations totalling more than 50% of the national total
</caption>
<thead>
<tr>
<th style="text-align:left;">
State
</th>
<th style="text-align:right;">
Population
</th>
<th style="text-align:right;">
Proportion
</th>
<th style="text-align:right;">
Cumulative
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
North Carolina
</td>
<td style="text-align:right;">
10,273,419
</td>
<td style="text-align:right;">
0.032
</td>
<td style="text-align:right;">
0.520
</td>
</tr>
<tr>
<td style="text-align:left;">
Georgia
</td>
<td style="text-align:right;">
10,429,379
</td>
<td style="text-align:right;">
0.032
</td>
<td style="text-align:right;">
0.552
</td>
</tr>
<tr>
<td style="text-align:left;">
Ohio
</td>
<td style="text-align:right;">
11,658,609
</td>
<td style="text-align:right;">
0.036
</td>
<td style="text-align:right;">
0.588
</td>
</tr>
<tr>
<td style="text-align:left;">
Illinois
</td>
<td style="text-align:right;">
12,802,023
</td>
<td style="text-align:right;">
0.039
</td>
<td style="text-align:right;">
0.627
</td>
</tr>
<tr>
<td style="text-align:left;">
Pennsylvania
</td>
<td style="text-align:right;">
12,805,537
</td>
<td style="text-align:right;">
0.039
</td>
<td style="text-align:right;">
0.666
</td>
</tr>
<tr>
<td style="text-align:left;">
New York
</td>
<td style="text-align:right;">
19,849,399
</td>
<td style="text-align:right;">
0.061
</td>
<td style="text-align:right;">
0.727
</td>
</tr>
<tr>
<td style="text-align:left;">
Florida
</td>
<td style="text-align:right;">
20,984,400
</td>
<td style="text-align:right;">
0.065
</td>
<td style="text-align:right;">
0.792
</td>
</tr>
<tr>
<td style="text-align:left;">
Texas
</td>
<td style="text-align:right;">
28,304,596
</td>
<td style="text-align:right;">
0.087
</td>
<td style="text-align:right;">
0.879
</td>
</tr>
<tr>
<td style="text-align:left;">
California
</td>
<td style="text-align:right;">
39,536,653
</td>
<td style="text-align:right;">
0.122
</td>
<td style="text-align:right;">
1.001
</td>
</tr>
</tbody>
</table>
<p>The resulting Senate composition:</p>
<ul>
<li>Lowest population states: 52</li>
<li>Intermediate population states: 26</li>
<li>Highest population states: 18</li>
<li>Lowest and intermediate population states together: 78</li>
</ul>
<p><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/class_map-1.png" width="672" /></p>
<p>Not only is population unevenly distributed, so is economic productivity, measured on per capita basis.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a>.</p>
<p><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/econ_map-1.png" width="672" /></p>
</div>
<div id="the-resulting-political-instability" class="section level1">
<h1>The Resulting Political Instability</h1>
<p>An arrangement in which 17.5% of the population can, if they agree or if dissenters can be replaced by other states, block legislation by the Congress is inherently unstable; a minority colalition of the 41 smallest states, 48.8% of the population, has unfettered power over the majority of the national population, 52% of the nine largest states.</p>
<p>The <em>representative democracy</em> model based on the 1790 model of indirect, free white male enfranchisement no longer serves as either a division of power contemplated when the Constitution was adopted in 1787, nor as a model that facilitates changes, preserves neeeded measures, dampens volatility and promotes confidence in risk taking in the face of unpredictable legal changes, or prevents the money and soft influence of special interests from gaming the decisions of the Senate. This part of the Constitution is failing, overlooked, and a danger to both principles of federalism and governing institutions that reflect the mediated will of the people. How to fix it is a debate that needs to begin.</p>
</div>
<div id="proposed" class="section level1">
<h1>Proposed</h1>
<p>What is a simple way to measure the potential of a minority of the population of the contemporary United States to elect the party in control the United States Senate? Similarly, how can the potential of those who are white, non-Hispanic to control the Senate be measured? My friend and former colleague <a href="https://goo.gl/LC3k1P">Todd Baker</a> suggested this topic.</p>
<p>In this essay, I propose four measures.</p>
<ol style="list-style-type: decimal">
<li>SLI, the state leverage index based on population alone</li>
<li>WLI, the white leverage index based on population alone</li>
<li><span class="math inline">\(TWLI\ =\ SLI\ *\ WLI\)</span></li>
<li>SPI, the state polarity index, based on the proportional vote of the winning candidate, averaged over the 2014, 2016 and 2018 elections.</li>
</ol>
<p>Based on the 2017 Census estimates the SLI and WLI are the simple ratios</p>
<center>
<span class="math inline">\(index = 1/(sub\_population/total\_population)\)</span>
</center>
<p><br></p>
<p>The third index is simply the product of the first two, which I call the Total White Leverage Index, <strong>TWLI</strong>.</p>
<p>The <strong>SPI</strong> is the weighted mean of the vote proportion received by the winning candidate in the 2014, 2016, and 2018 elections.[^Two two independent Senators, who caucus with the Democratic party were classified as Democrats.] To distinguish between parties, The Democratic winning candidates are expressed as a negative proportion; for example a Democratic candidate winning 54.1% of a vote is indexed as -0.541.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a></p>
<p>To illustrate, assume that the total population of the United States is 325,000,000 and a small state has a population of 700,000, of whom 600,000 are white, non-Hispanic.<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a>.</p>
<p>The SLI for the state would be 464.29 and its WLI would be 1.17. The TWLI would be 541.67.</p>
<p>The interpretation of <em>SLI</em> is that high scores indicate more potential influence on the composition of the Senate compared to an arrangement where Senate seats were allocated proportionally to national population. The interpretation of <em>WLI</em> is that high scores indicate more potential influence on the selection of a Senator in a given state held by white, non-Hispanic voters. The interpretation of <em>TWLI</em> combines the two measures, and high scores indicate more potential influence on the composition of the Senate by white, non-Hispanic voters compared to an arrangement where Senate seats were allocated proportionally to population.</p>
</div>
<div id="limitations-of-the-base-model" class="section level1">
<h1>Limitations of the Base Model</h1>
<p>Not all white, non-Hispanic voters vote alike, even within a state. We know that the proportion of each state’s population that is registered to vote or ineligible to vote (age, criminal history, citizenship status) varies. We know that propensity to vote varies. We know that it is possible to encourage or discourage voting within state based on precincts and the ways in which elections are administered.</p>
<p>The base model takes none of these real-world facts into account. The indices are intended solely to gauge <em>potential</em> for control of the Senate by a portion of the national population. It is merely a starting point from which additional variables can be added. Like all models, the base model derives its usefulness from simplifying reality.</p>
</div>
<div id="indices-by-state" class="section level1">
<h1>Indices by State</h1>
<div id="cumulative-effect-of-the-total-white-index-leverage-without-polarity" class="section level2">
<h2>Cumulative Effect of the Total White Index Leverage, Without Polarity</h2>
<p>The following chart shows the TWIL indices from greatest to lowest that measures the ability of each state, inversely proportionally to its population as a percent of the national total and proportional to its percentage of in-state white, non-Hispanic voters to</p>
<ul>
<li>Control 50 votes, permitting passing bills when the Vice President is of the same party</li>
<li>Control 60 votes, allowing cloture of debate</li>
<li>Control 66 votes, allowing over-ride of a Presidential veto, conviction of an impeached President, and the proposal of Constitutional amendments</li>
</ul>
<p>Some states above are <em>Red, Blue or Purple,</em> Taking into account the pre-2018 election composition of the Senate, the pending results of the 2018 elections, we will rearrange the table to reflect the new potential for majority white, non-Hispanic small states to achieve the control levels.</p>
<p>States with the cumulative TWLI to control the Senate constitute 16.17% of the U.S. population. By contrast, the 9 states with the lowest TWLI represent the 52.32%, a majority, of the U.S. population: California, Texas, Florida, New York, Pennsylvania, Illinois, Ohio, Georgia and North Carolina.</p>
</div>
</div>
<div id="tabular-results" class="section level1">
<h1>Tabular Results</h1>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:sli_tabular_results)State Leverage Indices by State
</caption>
<thead>
<tr>
<th style="text-align:left;">
State
</th>
<th style="text-align:right;">
SLI
</th>
<th style="text-align:right;">
WLI
</th>
<th style="text-align:right;">
TWLI
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Alabama
</td>
<td style="text-align:right;">
66.68
</td>
<td style="text-align:right;">
0.68
</td>
<td style="text-align:right;">
45
</td>
</tr>
<tr>
<td style="text-align:left;">
Alaska
</td>
<td style="text-align:right;">
439.34
</td>
<td style="text-align:right;">
0.64
</td>
<td style="text-align:right;">
281
</td>
</tr>
<tr>
<td style="text-align:left;">
Arizona
</td>
<td style="text-align:right;">
46.32
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
36
</td>
</tr>
<tr>
<td style="text-align:left;">
Arkansas
</td>
<td style="text-align:right;">
108.19
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
82
</td>
</tr>
<tr>
<td style="text-align:left;">
California
</td>
<td style="text-align:right;">
8.22
</td>
<td style="text-align:right;">
0.59
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
Colorado
</td>
<td style="text-align:right;">
57.97
</td>
<td style="text-align:right;">
0.84
</td>
<td style="text-align:right;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
Connecticut
</td>
<td style="text-align:right;">
90.58
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
69
</td>
</tr>
<tr>
<td style="text-align:left;">
Delaware
</td>
<td style="text-align:right;">
337.89
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:right;">
233
</td>
</tr>
<tr>
<td style="text-align:left;">
Florida
</td>
<td style="text-align:right;">
15.49
</td>
<td style="text-align:right;">
0.75
</td>
<td style="text-align:right;">
12
</td>
</tr>
<tr>
<td style="text-align:left;">
Georgia
</td>
<td style="text-align:right;">
31.16
</td>
<td style="text-align:right;">
0.59
</td>
<td style="text-align:right;">
18
</td>
</tr>
<tr>
<td style="text-align:left;">
Hawaii
</td>
<td style="text-align:right;">
227.68
</td>
<td style="text-align:right;">
0.25
</td>
<td style="text-align:right;">
57
</td>
</tr>
<tr>
<td style="text-align:left;">
Idaho
</td>
<td style="text-align:right;">
189.30
</td>
<td style="text-align:right;">
0.90
</td>
<td style="text-align:right;">
170
</td>
</tr>
<tr>
<td style="text-align:left;">
Illinois
</td>
<td style="text-align:right;">
25.39
</td>
<td style="text-align:right;">
0.71
</td>
<td style="text-align:right;">
18
</td>
</tr>
<tr>
<td style="text-align:left;">
Indiana
</td>
<td style="text-align:right;">
48.75
</td>
<td style="text-align:right;">
0.84
</td>
<td style="text-align:right;">
41
</td>
</tr>
<tr>
<td style="text-align:left;">
Iowa
</td>
<td style="text-align:right;">
103.32
</td>
<td style="text-align:right;">
0.90
</td>
<td style="text-align:right;">
93
</td>
</tr>
<tr>
<td style="text-align:left;">
Kansas
</td>
<td style="text-align:right;">
111.57
</td>
<td style="text-align:right;">
0.85
</td>
<td style="text-align:right;">
95
</td>
</tr>
<tr>
<td style="text-align:left;">
Kentucky
</td>
<td style="text-align:right;">
72.97
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
63
</td>
</tr>
<tr>
<td style="text-align:left;">
Louisiana
</td>
<td style="text-align:right;">
69.39
</td>
<td style="text-align:right;">
0.62
</td>
<td style="text-align:right;">
43
</td>
</tr>
<tr>
<td style="text-align:left;">
Maine
</td>
<td style="text-align:right;">
243.30
</td>
<td style="text-align:right;">
0.94
</td>
<td style="text-align:right;">
229
</td>
</tr>
<tr>
<td style="text-align:left;">
Maryland
</td>
<td style="text-align:right;">
53.70
</td>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:right;">
30
</td>
</tr>
<tr>
<td style="text-align:left;">
Massachusetts
</td>
<td style="text-align:right;">
47.38
</td>
<td style="text-align:right;">
0.79
</td>
<td style="text-align:right;">
37
</td>
</tr>
<tr>
<td style="text-align:left;">
Michigan
</td>
<td style="text-align:right;">
32.63
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
25
</td>
</tr>
<tr>
<td style="text-align:left;">
Minnesota
</td>
<td style="text-align:right;">
58.28
</td>
<td style="text-align:right;">
0.83
</td>
<td style="text-align:right;">
48
</td>
</tr>
<tr>
<td style="text-align:left;">
Mississippi
</td>
<td style="text-align:right;">
108.92
</td>
<td style="text-align:right;">
0.58
</td>
<td style="text-align:right;">
63
</td>
</tr>
<tr>
<td style="text-align:left;">
Missouri
</td>
<td style="text-align:right;">
53.16
</td>
<td style="text-align:right;">
0.82
</td>
<td style="text-align:right;">
44
</td>
</tr>
<tr>
<td style="text-align:left;">
Montana
</td>
<td style="text-align:right;">
309.40
</td>
<td style="text-align:right;">
0.89
</td>
<td style="text-align:right;">
275
</td>
</tr>
<tr>
<td style="text-align:left;">
Nebraska
</td>
<td style="text-align:right;">
169.28
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
147
</td>
</tr>
<tr>
<td style="text-align:left;">
Nevada
</td>
<td style="text-align:right;">
108.41
</td>
<td style="text-align:right;">
0.65
</td>
<td style="text-align:right;">
70
</td>
</tr>
<tr>
<td style="text-align:left;">
New Hampshire
</td>
<td style="text-align:right;">
242.05
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
225
</td>
</tr>
<tr>
<td style="text-align:left;">
New Jersey
</td>
<td style="text-align:right;">
36.09
</td>
<td style="text-align:right;">
0.68
</td>
<td style="text-align:right;">
25
</td>
</tr>
<tr>
<td style="text-align:left;">
New Mexico
</td>
<td style="text-align:right;">
155.66
</td>
<td style="text-align:right;">
0.76
</td>
<td style="text-align:right;">
118
</td>
</tr>
<tr>
<td style="text-align:left;">
New York
</td>
<td style="text-align:right;">
16.37
</td>
<td style="text-align:right;">
0.63
</td>
<td style="text-align:right;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
North Carolina
</td>
<td style="text-align:right;">
31.64
</td>
<td style="text-align:right;">
0.69
</td>
<td style="text-align:right;">
22
</td>
</tr>
<tr>
<td style="text-align:left;">
North Dakota
</td>
<td style="text-align:right;">
430.27
</td>
<td style="text-align:right;">
0.87
</td>
<td style="text-align:right;">
374
</td>
</tr>
<tr>
<td style="text-align:left;">
Ohio
</td>
<td style="text-align:right;">
27.88
</td>
<td style="text-align:right;">
0.81
</td>
<td style="text-align:right;">
23
</td>
</tr>
<tr>
<td style="text-align:left;">
Oklahoma
</td>
<td style="text-align:right;">
82.69
</td>
<td style="text-align:right;">
0.72
</td>
<td style="text-align:right;">
60
</td>
</tr>
<tr>
<td style="text-align:left;">
Oregon
</td>
<td style="text-align:right;">
78.46
</td>
<td style="text-align:right;">
0.84
</td>
<td style="text-align:right;">
66
</td>
</tr>
<tr>
<td style="text-align:left;">
Pennsylvania
</td>
<td style="text-align:right;">
25.38
</td>
<td style="text-align:right;">
0.81
</td>
<td style="text-align:right;">
21
</td>
</tr>
<tr>
<td style="text-align:left;">
Rhode Island
</td>
<td style="text-align:right;">
306.73
</td>
<td style="text-align:right;">
0.82
</td>
<td style="text-align:right;">
252
</td>
</tr>
<tr>
<td style="text-align:left;">
South Carolina
</td>
<td style="text-align:right;">
64.69
</td>
<td style="text-align:right;">
0.67
</td>
<td style="text-align:right;">
43
</td>
</tr>
<tr>
<td style="text-align:left;">
South Dakota
</td>
<td style="text-align:right;">
373.74
</td>
<td style="text-align:right;">
0.85
</td>
<td style="text-align:right;">
318
</td>
</tr>
<tr>
<td style="text-align:left;">
Tennessee
</td>
<td style="text-align:right;">
48.40
</td>
<td style="text-align:right;">
0.78
</td>
<td style="text-align:right;">
38
</td>
</tr>
<tr>
<td style="text-align:left;">
Texas
</td>
<td style="text-align:right;">
11.48
</td>
<td style="text-align:right;">
0.74
</td>
<td style="text-align:right;">
8
</td>
</tr>
<tr>
<td style="text-align:left;">
Utah
</td>
<td style="text-align:right;">
104.78
</td>
<td style="text-align:right;">
0.86
</td>
<td style="text-align:right;">
90
</td>
</tr>
<tr>
<td style="text-align:left;">
Vermont
</td>
<td style="text-align:right;">
521.16
</td>
<td style="text-align:right;">
0.94
</td>
<td style="text-align:right;">
490
</td>
</tr>
<tr>
<td style="text-align:left;">
Virginia
</td>
<td style="text-align:right;">
38.37
</td>
<td style="text-align:right;">
0.67
</td>
<td style="text-align:right;">
26
</td>
</tr>
<tr>
<td style="text-align:left;">
Washington
</td>
<td style="text-align:right;">
43.89
</td>
<td style="text-align:right;">
0.75
</td>
<td style="text-align:right;">
33
</td>
</tr>
<tr>
<td style="text-align:left;">
West Virginia
</td>
<td style="text-align:right;">
178.99
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
166
</td>
</tr>
<tr>
<td style="text-align:left;">
Wisconsin
</td>
<td style="text-align:right;">
56.08
</td>
<td style="text-align:right;">
0.85
</td>
<td style="text-align:right;">
48
</td>
</tr>
<tr>
<td style="text-align:left;">
Wyoming
</td>
<td style="text-align:right;">
561.05
</td>
<td style="text-align:right;">
0.91
</td>
<td style="text-align:right;">
511
</td>
</tr>
</tbody>
</table>
<p><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/sli_tabular_results-1.png" width="672" /></p>
<p><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/wli_tabular_results-1.png" width="672" /></p>
<p><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/twli_tabular_results-1.png" width="672" /></p>
<p><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/pli_tabular_results-1.png" width="672" /></p>
<div id="maps" class="section level2">
<h2>Maps</h2>
<p><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/mapping_wo_polarity-1.png" width="672" /><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/mapping_wo_polarity-2.png" width="672" /><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/mapping_wo_polarity-3.png" width="672" /></p>
<p><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/mapping_w_polarity-1.png" width="672" /><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/mapping_w_polarity-2.png" width="672" /><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/mapping_w_polarity-3.png" width="672" /><img src="/post/2018-11-10-population-and-ethnic-leverage-in-control-of-u-s-senate_files/figure-html/mapping_w_polarity-4.png" width="672" /></p>
</div>
<div id="color-decoding" class="section level2">
<h2>Color Decoding</h2>
<p>In the first map, ACS Estimates of 2017 Population of the 50 States, yellow indicate low population states, purple indicate the lowest tier of high population states, and red is the highest population state. Orange indicates the higher tier of relatively low population states,</p>
<p>In the second map, State Leverage Index, darker to ligher blues indicate lesser to greater voting potential leverage in Senate composition the lower influence tier. Red and oranges indicate lesser to greater voting leverage in Senate composition in the higher influence tier.</p>
<p>In the third map, State White Leverage Index, orange tints, from pale to dark indicate within state potential influence of white, non_Hispanic voters,indicate lower within-state influence, folowed by higher degrees of influence shown as gray, blue, and red shades.</p>
<p>In the fourth map, State Total White Leverage Index, increasing potential leverage of white, non-hispanic voters on within-state Senate composition range from shades of orange at the lowest through purple, blue, green and red.</p>
<p>In the fifth map, State Relative Total Leverage, increasing potential leverage of white, non-Hispanic voters on all-state Senate composition, range from shades of yellow/orange, representing the lowest, through purple, green and red, representing the highest.</p>
<p>In the sixth map, State Polarity Index, a spectrum from blue (Democratic) through Red (Republican) indicates the recent (2014-2018) polarity (measure by percentage margin in Senate elections), indicates the observed polarity.</p>
<p>In the seventh map, State Polarity Index Weighted State Leverage Index the same spectrum is used. It indicates the lessened effect of the White Leverage Index on the State Polarity Index, considered within-state.</p>
<p>In the eight map, State Polarity Index Weighted White Leverage Index, shades of red and blue, respectively, indicates potential white, non-Hispanic influence on the within-state Senate results. Grays are neutral.</p>
<p>In the ninth map, State Polarity Index Weighted Total White Leverage Index, shades of red and blue indicate propensity of white, non_Hispanic voters to be associated with margins of victory of Republican and Democratic candidates, respectively. Shades of grey indicate a neutral effect of the combination of SLI, WLI, TWLI and polarity.</p>
</div>
</div>
<div id="conclusions" class="section level1">
<h1>Conclusions</h1>
<p>White, non-Hispanic voters in the group of states constituting the minority of the total US population, have the potential to create 22 Senate seats for Republicans based on recent history based on their WLI and polarity. The remaining minority states have the potential to create 20 Senate seats for Democrats on the same basis. The remaining 20 seats controlled by minority states are insufficient to create control of the Senate without increasing WLI, polarity or both in the absence of 8-9 (depending on the control of the Presidency) majority states.</p>
<p>In otherwords, under current conditions and the assumptions in this analysis, the Senate will be closely divided. Neither party will achieve cloture or impeachment level control. The Senate is divided into three classes; different groups states vote for Senate each year. Demographic changes may affect WLI, as relative composition of incoming voters changes through natural increase or decrease and net migration, the composition of outgoing voters change as a function of migration or death, propensitity to vote changes, and polarity changes. None of these dynamic factors are included in this essay.</p>
</div>
<div id="appendix" class="section level1">
<h1>Appendix</h1>
<div id="disclosure" class="section level2">
<h2>Disclosure</h2>
<p>I am not a political scientist and I have not reviewed the literature. My training is as a lawyer and an applied statistician (also known as a <em>data scientist</em>.) The purpose of this essay is to provide a beginning basis for assessment of future control frameworks of the U.S. Senate. It is only one potential beginning point. The question of how to assure inclusion of all perspectives on matters of national interest vs. matters of predominanty state interest is a central problem of how we should govern ourselves. Small states deserve a voice and large states require a counterbalance. We have managed, through extra-constitutional means, such as campaign finance and interest group liberalism in the Altshuler sense, to introduce a private sector factor into the governance equation in the Senate that is neither democratic nor representative. This should concern partisans of all degree.</p>
</div>
<div id="sources" class="section level2">
<h2>Sources</h2>
<p><a href="%22https://gist.githubusercontent.com/technocrat/93470bf9abead06ef926/raw/f652f8171374e7808455f42167f5480ea15f7f4e/state_fips_postal.csv%22">Postal abbreviations</a> were prepared by the author, based on official sources.</p>
<p>The 2017 population estimates were obtained from the U.S. Census American Community Survey(<a href="https://goo.gl/9DLfZu" class="uri">https://goo.gl/9DLfZu</a>&quot;) with queries to produce white, non-Hispanic population and total population estimates.</p>
<p>Margins of Senate elections in 2014 and 2016 were obtained from <a href="https://politico.com">Politico</a>, by cut-paste-and-edit. Those for 2018 were obtained similarly from the <a href="wapo.com">Washington Post</a>.</p>
<p>Geographic information was included in the U.S. Census American Community Survey <em>via</em> <strong>tidycensus</strong>.</p>
<p>2018 Q2 GDP <a href="https://goo.gl/Jc6XyK" class="uri">https://goo.gl/Jc6XyK</a> Bureau of Economic Statistics</p>
</div>
<div id="credits" class="section level2">
<h2>Credits</h2>
<p>Except for standard Unix-derivated manual adjustments, this essay is based on the <strong>R</strong> programming language and the following contributed packages.</p>
<ol style="list-style-type: decimal">
<li>R Development Core Team (2008). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. ISBN 3-900051-07-0, URL <a href="http://www.R-project.org" class="uri">http://www.R-project.org</a>.</li>
<li>Simon Urbanek and Jeffrey Horner (2015). Cairo: R graphics device using cairo graphics library for creating high-quality bitmap (PNG, JPEG, TIFF), vector (PDF, SVG, PostScript) and display (X11 and Win32) output. R package version 1.5-9. <a href="https://CRAN.R-project.org/package=Cairo" class="uri">https://CRAN.R-project.org/package=Cairo</a></li>
<li>H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2016</li>
<li>Bob Rudis (2018). hrbrthemes: Additional Themes, Theme Components and Utilities for ‘ggplot2’. R package version 0.5.0.1. <a href="https://CRAN.R-project.org/package=hrbrthemes" class="uri">https://CRAN.R-project.org/package=hrbrthemes</a></li>
<li>Hao Zhu (2018). kableExtra: Construct Complex Table with ‘kable’ and Pipe Syntax. R package version 0.9.0. <a href="https://CRAN.R-project.org/package=kableExtra" class="uri">https://CRAN.R-project.org/package=kableExtra</a></li>
<li>Yihui Xie (2018). knitr: A General-Purpose Package for Dynamic Report Generation in R. R package version 1.20. Yihui Xie (2015) Dynamic Documents with R and knitr. 2nd edition. Chapman and Hall/CRC. ISBN 978-1498716963 Yihui Xie (2014) knitr: A Comprehensive Tool for Reproducible Research in R. In Victoria 6. Stodden, Friedrich Leisch and Roger D. Peng, editors, Implementing Reproducible Computational Research. Chapman and Hall/CRC. ISBN 978-1466561595</li>
<li>Erich Neuwirth (2014). RColorBrewer: ColorBrewer Palettes. R package version 1.1-2. <a href="https://CRAN.R-project.org/package=RColorBrewer" class="uri">https://CRAN.R-project.org/package=RColorBrewer</a></li>
<li>Hadley Wickham (2018). scales: Scale Functions for Visualization. R package version 1.0.0.https://CRAN.R-project.org/package=scales</li>
<li>Pebesma, E., 2018. Simple Features for R: Standardized Support for Spatial Vector Data. The R Journal, <a href="https://journal.r-project.org/archive/2018/RJ-2018-009/" class="uri">https://journal.r-project.org/archive/2018/RJ-2018-009/</a></li>
<li>Kyle Walker (2018). tidycensus: Load US Census Boundary and Attribute Data as ‘tidyverse’ and22 ‘sf’-Ready Data Frames. R package version 0.8.1. <a href="https://CRAN.R-project.org/package=tidycensus" class="uri">https://CRAN.R-project.org/package=tidycensus</a></li>
<li>Hadley Wickham (2017). tidyverse: Easily Install and Load the ‘Tidyverse’. R package version 1.2.1. <a href="https://CRAN.R-project.org/package=tidyverse" class="uri">https://CRAN.R-project.org/package=tidyverse</a></li>
</ol>
</div>
<div id="reproducible-code" class="section level2">
<h2>Reproducible Code</h2>
<p>[to be added on publication]</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Source for 1790 Census: 1790 Census: <a href="https://en.wikipedia.org/wiki/1790_United_States_Census" class="uri">https://en.wikipedia.org/wiki/1790_United_States_Census</a><a href="#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>This is a simplified picture. All free white males aged 16 or over are here classified as voters, although only a portion met the property qualifications. The vote for Senators was indirect, through selection by the elected state legislatures, until the adoption of the Seventeenth Amendment in 1913.<a href="#fnref2" class="footnote-back">↩</a></p></li>
<li id="fn3"><p>Although we often think of the United States as a democracy, the word appears neither in the Declaration of Independence, <em>The Federalist Papers</em>, the <em>Anti-Federalist Papers</em>, James Madison’s minutes of the Constitutional Convention, nor, in the Constitution itself or prominently in the leading United States Supreme Court decisions interpreting it (<em>see</em> Michael J. Garcia <em>et al.</em>, <em>The Constitution of the United States of America Analysis and Interpretation, Centennial Edition, Interim Edition: Analysis Of Cases Decided By The Supreme Court Of The United States To August 26, 2017</em>, 2017, Government Printing Office, <a href="https://goo.gl/TqfCJG" class="uri">https://goo.gl/TqfCJG</a>
<em>see also</em> Gordon S. Wood, <em>The Creation of the American Republic</em>, 1776-1787, 1998, University of North Carolina Press, Chapel Hill, Chapter V, The Nature of Representation, Ambassadors to an Extraneous Power)<a href="#fnref3" class="footnote-back">↩</a></p></li>
<li id="fn4"><p>When [Lyndon Johnson] arrived in the Senate [in 1949], that institution had for decades been almost a joke—an object of ridicule to cartoonists and comedians, of frustration and despair to historians and political scientists. Hamstrung by archaic rules and customs which it was determined to keep unchanged, it seemed hopelessly unable to adapt to the new needs of a modern, more complex world, and its rigid adherence to a seniority system thoroughly drained it of energy and vitality and initiative while keeping in some of its most influential positions men so elderly that wags called it the “senility system.” Robert Caro, <em>Master of the Senate</em>, 2002, A.A. Knopf, New York, at <em>xxiii</em><a href="#fnref4" class="footnote-back">↩</a></p></li>
<li id="fn5"><p>Bureau of Economic Statistics Second Quarter Gross Domestic Product by State per 100,000 population<a href="#fnref5" class="footnote-back">↩</a></p></li>
<li id="fn6"><p>A Republican victory is reported as a positive proportion, and a Democratic victory as a negative proportion; the results of the Mississippi runoff are unknown at this writing, but are likely to be close to 0.5 or -0.5 and do not materially affect the analysis.<a href="#fnref6" class="footnote-back">↩</a></p></li>
<li id="fn7"><p>Actual estimates will be used in the analysis to follow<a href="#fnref7" class="footnote-back">↩</a></p></li>
</ol>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdn.bootcss.com/highlight.js/9.11.0/highlight.min.js"></script>



<script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/r.min.js"></script>
<script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

