---
title: Nathan Yau on the challenges of thematic maps
author: Richard Careaga
date: '2018-08-09'
slug: nathan-yau-on-the-challenges-of-thematic-maps
categories:
  - Data Science
tags: [geospatial]
---
If you are a paying member of [Flowing Data](https:flowingdata.com) (well worth the modest subscription), you will have received his email, reproduced at a [paywalled](https://flowingdata.com/2018/08/09/detailed-intentions/) portion of the site.

He gives a detailed critique of a precinct-by-precinct [map](https://www.nytimes.com/interactive/2018/upshot/election-2016-voting-precinct-maps.html#10.95/47.678/-122.200/106446) of the 2016 presidential election, nationwide, showing the number of votes for Trump and Clinton and the nearest precinct in which the opposing candidate was in the majority.

He compares what the map purports to show with what it actually *does* show, which is the raw total of votes (ho-hum, we've known that for a long time) and the *percentages.* What the map fails to show is **population density**.

> More concretely, a 100-person precinct that voted 20 percent for Trump still had more Trump votes than a 10-person precinct that voted 100 percent for Trump.

In other words, the larger precinct is "blue," while the smaller precinct is "red." But *twice* as red by headcount. 

My own observation: Combined with our innate overperception of area and failing to weight voting results by percentage, we perceive a sea of red surrounding a few islands of blue. However, the national total blue vote was higher.
